doc-valid-idents = [
    "ClickHouse",
    "OpenSearch",
    "MLCroissant",
    "PubMed",
    "ChEMBL",
    "DrugBank",
    "Gene2Phenotype",
    "MoA",
    "ClinGen",
    "ClinVar",
    "IntOGen",
    "PanelApp",
    "CRISPRbrain",
    "PhenoDigm",
    "UniProt",
    "AlphaFold",
    "GnomAD",
    "ProbeMiner",
    "SwissProt",
    ".."  # this appends default valid idents
]
