query study_single {
    studies(
        diseaseIds: ["MONDO_0004992"]
        enableIndirect: true
        page: { index: 0, size: 10 }
    ) {
        total
        items {
            id
            nSamples
            traitFromSource
            diseases {
                id
                name
                children {
                    id
                    name
                }
            }
        }
    }
}

# ---

query study_multiple {
    studies(
        studyIds: ["GCST90002357", "GCST004988", "GCST006979", "GCST90239655"]
        # filter: { studyId: { contains: "GCST" } }
        # search: "PLA"
        # sort: N_SAMPLES
        # dir: DESC
        page: { index: 0, size: 10 }
    ) {
        total
        items {
            id
            nSamples
            traitFromSource
        }
    }
}

# ---

query meta {
    meta {
        name
        product
        apiVersion {
            year
            month
            revision
        }
        dataVersion {
            year
            month
            revision
        }
        dataNamespace
        downloads
    }
}

# ---

query disease_with_evidence {
    disease(efoId: "EFO_0000266") {
        id
        name
        phenotypes(page: { index: 0, size: 1000 }) {
            total
            items {
                evidence {
                    aspect
                    bioCuration
                    diseaseFromSourceId
                    diseaseFromSource
                    frequency
                    modifiers {
                        id
                        name
                        description
                        namespace
                    }
                    onset {
                        id
                        name
                        description
                    }
                    sex
                }
                phenotypeHPO {
                    id
                    name
                    description
                    namespace
                }
                phenotypeEFO {
                    id
                    name
                }
            }
        }
    }
}

# ---

query search {
    search(
        queryString: "rheumatoid"
        page: { index: 0, size: 10 }
        entityNames: ["disease", "study"]
    ) {
        total
        hits {
            id
            name
            entity
            category
            description
            # keywords
            prefixes
            ngrams
            highlights
            multiplier
            score
            object {
                ... on Disease {
                    id
                    name
                    description
                }
                ... on Study {
                    id
                    publicationTitle
                }
            }
        }
        aggregations {
            total
            entities {
                name
                total
                categories {
                    name
                    total
                }
            }
        }
    }
}

# ---

query facets {
    facets(
        queryString: "arth"
        entityNames: ["disease"]
        category: "Disease"
        page: { index: 0, size: 10 }
    ) {
        total
        categories {
            total
            name
        }
        hits {
            id
            datasourceId
            category
            highlights
            score
            # entityIds
        }
    }
}

# ---

query study_with_stats($dids: [String!]) {
    studies(
        studyIds: $dids
        enableIndirect: true
        page: { index: 0, size: 10000 }
    ) {
        total
        items {
            id
            publicationTitle
        }
        stats {
            studyType {
                value
                count
            }
        }
    }
}

# {
#   "dids": [
#     "FINNGEN_R12_C3_ADRENAL_GLAND_EXALLC",
#     "FINNGEN_R12_C3_AML_EXALLC",
#     "FINNGEN_R12_C3_AML_MDS",
#     "FINNGEN_R12_C3_AML_MDS_EXALLC",
#     "FINNGEN_R12_C3_ANUS_ANALCANAL_EXALLC",
#     "FINNGEN_R12_C3_BASAL_CELL_CARCINOMA_EXALLC",
#     "FINNGEN_R12_C3_BASAL_CELL_CARCINOMA_INCLAVO_EXALLC",
#     "FINNGEN_R12_C3_BILIARY_GALLBLADDER_EXALLC",
#     "FINNGEN_R12_C3_BLADDER_EXALLC",
#     "FINNGEN_R12_C3_BONE_CARTILAGE_EXALLC",
#     "FINNGEN_R12_C3_BRAIN_EXALLC",
#     "FINNGEN_R12_C3_BREAST_ERNEG_EXALLC",
#     "FINNGEN_R12_C3_BREAST_ERPLUS_EXALLC",
#     "FINNGEN_R12_C3_BREAST_EXALLC",
#     "FINNGEN_R12_C3_BRONCHUS_LUNG_EXALLC",
#     "FINNGEN_R12_C3_CANCER_EXALLC",
#     "FINNGEN_R12_C3_CERVIX_ADENO_EXALLC",
#     "FINNGEN_R12_C3_CERVIX_SQUAM_EXALLC",
#     "FINNGEN_R12_C3_CERVIX_UTERI_EXALLC",
#     "FINNGEN_R12_C3_CHONDROSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_CML_EXALLC",
#     "FINNGEN_R12_C3_COLON_ADENO_EXALLC",
#     "FINNGEN_R12_C3_COLON_EXALLC",
#     "FINNGEN_R12_C3_COLORECTAL_ADENO_EXALLC",
#     "FINNGEN_R12_C3_COLORECTAL_EXALLC",
#     "FINNGEN_R12_C3_CORPUS_UTERI_EXALLC",
#     "FINNGEN_R12_C3_EYE_ADNEXA_EXALLC",
#     "FINNGEN_R12_C3_FIBROSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_GBM_ASTROCYTOMA_EXALLC",
#     "FINNGEN_R12_C3_GBM_EXALLC",
#     "FINNGEN_R12_C3_HEAD_AND_NECK_EXALLC",
#     "FINNGEN_R12_C3_HEPATOCELLU_CARC_EXALLC",
#     "FINNGEN_R12_C3_HYPOPHARYNX_EXALLC",
#     "FINNGEN_R12_C3_KAPOSI_SARCOMA_EXALLC",
#     "FINNGEN_R12_C3_KIDNEY_CHROMOPHOBE_EXALLC",
#     "FINNGEN_R12_C3_KIDNEY_CLEAR_CELL_CARCINOMA_EXALLC",
#     "FINNGEN_R12_C3_KIDNEY_NOTRENALPELVIS_EXALLC",
#     "FINNGEN_R12_C3_KIDNEY_PAPILLARYADENO_EXALLC",
#     "FINNGEN_R12_C3_LEIOMYOSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_LIPOSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_LIP_EXALLC",
#     "FINNGEN_R12_C3_LUNG_NEUROENDO_EXALLC",
#     "FINNGEN_R12_C3_LUNG_NONSMALL_EXALLC",
#     "FINNGEN_R12_C3_MELANOMA_SKIN_EXALLC",
#     "FINNGEN_R12_C3_MULT_MYELOMA_EXALLC",
#     "FINNGEN_R12_C3_NASAL_CAVITY_SINUSES_EXALLC",
#     "FINNGEN_R12_C3_NASOPHARYNX_EXALLC",
#     "FINNGEN_R12_C3_NSCLC_ADENO_EXALLC",
#     "FINNGEN_R12_C3_NSCLC_SQUAM_EXALLC",
#     "FINNGEN_R12_C3_OESOPHAGUS_EXALLC",
#     "FINNGEN_R12_C3_ORALCAVITY_EXALLC",
#     "FINNGEN_R12_C3_OROPHARYNG_EXALLC",
#     "FINNGEN_R12_C3_OSTEOSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_OTHER_SKIN_EXALLC",
#     "FINNGEN_R12_C3_OVARY_ENDOMETROID_EXALLC",
#     "FINNGEN_R12_C3_OVARY_EXALLC",
#     "FINNGEN_R12_C3_OVARY_SEROUS_EXALLC",
#     "FINNGEN_R12_C3_PANCREAS_ADENO_DUCTAL_EXALLC",
#     "FINNGEN_R12_C3_PANCREAS_EXALLC",
#     "FINNGEN_R12_C3_PANCREAS_NEUROENDOCRINE_EXALLC",
#     "FINNGEN_R12_C3_PAROTIDGLAND_EXALLC",
#     "FINNGEN_R12_C3_PENIS_EXALLC",
#     "FINNGEN_R12_C3_PROSTATE_EXALLC",
#     "FINNGEN_R12_C3_RECTUM_ADENO",
#     "FINNGEN_R12_C3_RECTUM_ADENO_MUCINO_EXALLC",
#     "FINNGEN_R12_C3_RECTUM_EXALLC",
#     "FINNGEN_R12_C3_RECTUM_NEUROENDOCRINE_EXALLC",
#     "FINNGEN_R12_C3_RENAL_PELVIS_EXALLC",
#     "FINNGEN_R12_C3_RHABDOMYOSARCOMA_EXALLC",
#     "FINNGEN_R12_C3_SCLC_EXALLC",
#     "FINNGEN_R12_C3_SKIN_EXALLC",
#     "FINNGEN_R12_C3_SMALL_INTESTINE_ADENO_EXALLC",
#     "FINNGEN_R12_C3_SMALL_INTESTINE_EXALLC",
#     "FINNGEN_R12_C3_SMALL_INTESTINE_NEUROENDOCRINE_EXALLC",
#     "FINNGEN_R12_C3_SPINAL_CORD_CRANIAL_AND_OTHER_CNS_EXALLC",
#     "FINNGEN_R12_C3_SQUOMOUS_CELL_CARCINOMA_SKIN_EXALLC",
#     "FINNGEN_R12_C3_STOMACH_ADENO_EXALLC",
#     "FINNGEN_R12_C3_STOMACH_EXALLC",
#     "FINNGEN_R12_C3_STOMACH_NEUROENDOCRINE_EXALLC",
#     "FINNGEN_R12_C3_TESTIS_EXALLC",
#     "FINNGEN_R12_C3_TESTIS_SEMINOMA_EXALLC",
#     "FINNGEN_R12_C3_THYMUS_EXALLC",
#     "FINNGEN_R12_C3_THYROID_FOLLICULAR_EXALLC",
#     "FINNGEN_R12_C3_THYROID_GLAND_EXALLC",
#     "FINNGEN_R12_C3_THYROID_MEDULLARY_EXALLC",
#     "FINNGEN_R12_C3_THYROID_PAPILLARY_ADENO_EXALLC",
#     "FINNGEN_R12_C3_TONSIL_BASETONGUE_EXALLC",
#     "FINNGEN_R12_C3_URETER_EXALLC",
#     "FINNGEN_R12_C3_URINARY_TRACT_EXALLC",
#     "FINNGEN_R12_C3_VULVA_EXALLC",
#     "FINNGEN_R12_C3_WILMS_TUMOR",
#     "FINNGEN_R12_C3_WILMS_TUMOR_EXALLC",
#     "FINNGEN_R12_CD2_BENIGN_FEMALE_GEN_NOS",
#     "FINNGEN_R12_CD2_BENIGN_FEMALE_GEN_OTH",
#     "FINNGEN_R12_CD2_INSITU_BLADDER_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_BREAST_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_BREAST_INTRADUCTAL_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_BREAST_LOBULAR_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_CERVIX_UTERI_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_COLON_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_ENDOMETRIUM_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_LARYNX_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_ORALCAVITY_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_PENIS_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_PROSTATE_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_RECTUM_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_SKIN_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_VAGINA_EXALLC",
#     "FINNGEN_R12_CD2_INSITU_VULVA_EXALLC",
#     "FINNGEN_R12_CD2_MONOCYTIC_LEUKAEMIA_EXALLC",
#     "FINNGEN_R12_CD2_MULTIPLE_MYELOMA_PLASMA_CELL_EXALLC",
#     "FINNGEN_R12_CD2_MYELOID_LEUKAEMIA_EXALLC",
#     "FINNGEN_R12_CD2_UVEAMELANOMA_EXALLC",
#     "FINNGEN_R12_CHRONMYELOPRO",
#     "FINNGEN_R12_CML",
#     "FINNGEN_R12_M13_PAGET",
#     "FINNGEN_R12_MYELOPROF_NONCML",
#     "FINNGEN_R12_N14_MALEGEN",
#     "FINNGEN_R12_POLYCYTVERA",
#     "FINNGEN_R12_THROMBOCYTAEMIA",
#     "GCST000011",
#     "GCST000017",
#     "GCST000019",
#     "GCST000035",
#     "GCST000036",
#     "GCST000037",
#     "GCST000050",
#     "GCST000052",
#     "GCST000053",
#     "GCST000079",
#     "GCST000095",
#     "GCST000113",
#     "GCST000128",
#     "GCST000152",
#     "GCST000153",
#     "GCST000154",
#     "GCST000162",
#     "GCST000168",
#     "GCST000169",
#     "GCST000170",
#     "GCST000172",
#     "GCST000187",
#     "GCST000223",
#     "GCST000231",
#     "GCST000233",
#     "GCST000249",
#     "GCST000256",
#     "GCST000257",
#     "GCST000270",
#     "GCST000307",
#     "GCST000318",
#     "GCST000335",
#     "GCST000343",
#     "GCST000357",
#     "GCST000365",
#     "GCST000414",
#     "GCST000416",
#     "GCST000439",
#     "GCST000440",
#     "GCST000454",
#     "GCST000455",
#     "GCST000456",
#     "GCST000459",
#     "GCST000466",
#     "GCST000472",
#     "GCST000488",
#     "GCST000489",
#     "GCST000506",
#     "GCST000574",
#     "GCST000633",
#     "GCST000637",
#     "GCST000639",
#     "GCST000640",
#     "GCST000678",
#     "GCST000686",
#     "GCST000701",
#     "GCST000709",
#     "GCST000722",
#     "GCST000745",
#     "GCST000750",
#     "GCST000752",
#     "GCST000761",
#     "GCST000776",
#     "GCST000777",
#     "GCST000777_2",
#     "GCST000800",
#     "GCST000801",
#     "GCST000802",
#     "GCST000810",
#     "GCST000811",
#     "GCST000815",
#     "GCST000824",
#     "GCST000842",
#     "GCST000843",
#     "GCST000844",
#     "GCST000846",
#     "GCST000867",
#     "GCST000871",
#     "GCST000896",
#     "GCST000902",
#     "GCST000907",
#     "GCST000947",
#     "GCST000948",
#     "GCST000952",
#     "GCST000989",
#     "GCST001012",
#     "GCST001028",
#     "GCST001041",
#     "GCST001058",
#     "GCST001063",
#     "GCST001067",
#     "GCST001078",
#     "GCST001089",
#     "GCST001124",
#     "GCST001140",
#     "GCST001147",
#     "GCST001148",
#     "GCST001153",
#     "GCST001161",
#     "GCST001193",
#     "GCST001194",
#     "GCST001210",
#     "GCST001224",
#     "GCST001250",
#     "GCST001258",
#     "GCST001283",
#     "GCST001298",
#     "GCST001300",
#     "GCST001331",
#     "GCST001338",
#     "GCST001348",
#     "GCST001350",
#     "GCST001370",
#     "GCST001373",
#     "GCST001373_2",
#     "GCST001382",
#     "GCST001407",
#     "GCST001420",
#     "GCST001426",
#     "GCST001457",
#     "GCST001470",
#     "GCST001489",
#     "GCST001500",
#     "GCST001543",
#     "GCST001544",
#     "GCST001556",
#     "GCST001589",
#     "GCST001603",
#     "GCST001609",
#     "GCST001638",
#     "GCST001646",
#     "GCST001648",
#     "GCST001667",
#     "GCST001672",
#     "GCST001674",
#     "GCST001683",
#     "GCST001690",
#     "GCST001700",
#     "GCST001702",
#     "GCST001714",
#     "GCST001718",
#     "GCST001718_2",
#     "GCST001718_3",
#     "GCST001719",
#     "GCST001721",
#     "GCST001731",
#     "GCST001734",
#     "GCST001740",
#     "GCST001749",
#     "GCST001750",
#     "GCST001775",
#     "GCST001787",
#     "GCST001792",
#     "GCST001794",
#     "GCST001816",
#     "GCST001827",
#     "GCST001831",
#     "GCST001832",
#     "GCST001869",
#     "GCST001879",
#     "GCST001900",
#     "GCST001906",
#     "GCST001907",
#     "GCST001916",
#     "GCST001917",
#     "GCST001930",
#     "GCST001937",
#     "GCST001941",
#     "GCST001942",
#     "GCST001978",
#     "GCST002010",
#     "GCST002022",
#     "GCST002023",
#     "GCST002024",
#     "GCST002032",
#     "GCST002056",
#     "GCST002082",
#     "GCST002099",
#     "GCST002102",
#     "GCST002140",
#     "GCST002210",
#     "GCST002231",
#     "GCST002232",
#     "GCST002234",
#     "GCST002240",
#     "GCST002243",
#     "GCST002264",
#     "GCST002265",
#     "GCST002266",
#     "GCST002267",
#     "GCST002272",
#     "GCST002273",
#     "GCST002305",
#     "GCST002331",
#     "GCST002340",
#     "GCST002346",
#     "GCST002392",
#     "GCST002397",
#     "GCST002405",
#     "GCST002411",
#     "GCST002412",
#     "GCST002413",
#     "GCST002415",
#     "GCST002421",
#     "GCST002431",
#     "GCST002431_2",
#     "GCST002431_3",
#     "GCST002454",
#     "GCST002460",
#     "GCST002466",
#     "GCST002466_2",
#     "GCST002466_3",
#     "GCST002474",
#     "GCST002512",
#     "GCST002513",
#     "GCST002528",
#     "GCST002537",
#     "GCST002553",
#     "GCST002561",
#     "GCST002568",
#     "GCST002576",
#     "GCST002577",
#     "GCST002596",
#     "GCST002597",
#     "GCST002606",
#     "GCST002614",
#     "GCST002645",
#     "GCST002662",
#     "GCST002727",
#     "GCST002735",
#     "GCST002739",
#     "GCST002748",
#     "GCST002753",
#     "GCST002816",
#     "GCST002820",
#     "GCST002820_2",
#     "GCST002820_3",
#     "GCST002821",
#     "GCST002821_2",
#     "GCST002835",
#     "GCST002840",
#     "GCST002842",
#     "GCST002847",
#     "GCST002861",
#     "GCST002861_2",
#     "GCST002861_3",
#     "GCST002873",
#     "GCST002886",
#     "GCST002890",
#     "GCST002895",
#     "GCST002901",
#     "GCST002902",
#     "GCST002903",
#     "GCST002919",
#     "GCST002921",
#     "GCST002922",
#     "GCST002944",
#     "GCST002967",
#     "GCST002990",
#     "GCST002991",
#     "GCST002992",
#     "GCST003007",
#     "GCST003009",
#     "GCST003010",
#     "GCST003017",
#     "GCST003049",
#     "GCST003051",
#     "GCST003057",
#     "GCST003058",
#     "GCST003061",
#     "GCST003100",
#     "GCST003148",
#     "GCST003189",
#     "GCST003208",
#     "GCST003209",
#     "GCST003218",
#     "GCST003220",
#     "GCST003227",
#     "GCST003228",
#     "GCST003229",
#     "GCST003230",
#     "GCST003231",
#     "GCST003325",
#     "GCST003326",
#     "GCST003327",
#     "GCST003328",
#     "GCST003384",
#     "GCST003385",
#     "GCST003386",
#     "GCST003387",
#     "GCST003420",
#     "GCST003422",
#     "GCST003436",
#     "GCST003494",
#     "GCST003520",
#     "GCST003524",
#     "GCST003525",
#     "GCST003541",
#     "GCST003565",
#     "GCST003585",
#     "GCST003586",
#     "GCST003587",
#     "GCST003588",
#     "GCST003605",
#     "GCST003655",
#     "GCST003726",
#     "GCST003739",
#     "GCST003740",
#     "GCST003758",
#     "GCST003775",
#     "GCST003776",
#     "GCST003777",
#     "GCST003780",
#     "GCST003781",
#     "GCST003782",
#     "GCST003794",
#     "GCST003799",
#     "GCST003842",
#     "GCST003845",
#     "GCST003857",
#     "GCST003858",
#     "GCST003859",
#     "GCST003873",
#     "GCST003874",
#     "GCST004044",
#     "GCST004045",
#     "GCST004099",
#     "GCST004113",
#     "GCST004134",
#     "GCST004144",
#     "GCST004160",
#     "GCST004168",
#     "GCST004169",
#     "GCST004228",
#     "GCST004229",
#     "GCST004347",
#     "GCST004348",
#     "GCST004349",
#     "GCST004414",
#     "GCST004415",
#     "GCST004416",
#     "GCST004417",
#     "GCST004418",
#     "GCST004419",
#     "GCST004462",
#     "GCST004478",
#     "GCST004479",
#     "GCST004480",
#     "GCST004481",
#     "GCST004483",
#     "GCST004485",
#     "GCST004661",
#     "GCST004710",
#     "GCST004736",
#     "GCST004744",
#     "GCST004746",
#     "GCST004747",
#     "GCST004748",
#     "GCST004749",
#     "GCST004750",
#     "GCST004753",
#     "GCST004754",
#     "GCST004798",
#     "GCST004833",
#     "GCST004836",
#     "GCST004837",
#     "GCST004839",
#     "GCST004840",
#     "GCST004895",
#     "GCST004896",
#     "GCST004897",
#     "GCST004948",
#     "GCST004949",
#     "GCST004950",
#     "GCST004982",
#     "GCST004988",
#     "GCST005075",
#     "GCST005077",
#     "GCST005106",
#     "GCST005110",
#     "GCST005111",
#     "GCST005112",
#     "GCST005148",
#     "GCST005149",
#     "GCST005150",
#     "GCST005152",
#     "GCST005158",
#     "GCST005267",
#     "GCST005275",
#     "GCST005309",
#     "GCST005434",
#     "GCST005570",
#     "GCST005591",
#     "GCST005746",
#     "GCST005747",
#     "GCST005768",
#     "GCST005786",
#     "GCST005855",
#     "GCST005856",
#     "GCST005858",
#     "GCST005860",
#     "GCST005896",
#     "GCST005900",
#     "GCST005901",
#     "GCST005906",
#     "GCST005909",
#     "GCST005910",
#     "GCST005911",
#     "GCST006035",
#     "GCST006037",
#     "GCST006080",
#     "GCST006081",
#     "GCST006082",
#     "GCST006083",
#     "GCST006084",
#     "GCST006085",
#     "GCST006086",
#     "GCST006087",
#     "GCST006088",
#     "GCST006089",
#     "GCST006131",
#     "GCST006398",
#     "GCST006399",
#     "GCST006400",
#     "GCST006411",
#     "GCST006413",
#     "GCST006432",
#     "GCST006464",
#     "GCST006465",
#     "GCST006466",
#     "GCST006467",
#     "GCST006480",
#     "GCST006525",
#     "GCST006530",
#     "GCST006531",
#     "GCST006532",
#     "GCST006707",
#     "GCST006719",
#     "GCST006866",
#     "GCST006985",
#     "GCST007119",
#     "GCST007235",
#     "GCST007236",
#     "GCST007239",
#     "GCST007302",
#     "GCST007414",
#     "GCST007415",
#     "GCST007416",
#     "GCST007417",
#     "GCST007418",
#     "GCST007419",
#     "GCST007420",
#     "GCST007505",
#     "GCST007506",
#     "GCST007514",
#     "GCST007552",
#     "GCST007728",
#     "GCST007856",
#     "GCST007896",
#     "GCST007992",
#     "GCST008216",
#     "GCST008217",
#     "GCST008218",
#     "GCST008219",
#     "GCST008220",
#     "GCST008221",
#     "GCST008222",
#     "GCST008224",
#     "GCST008225",
#     "GCST008226",
#     "GCST008231",
#     "GCST008371",
#     "GCST008372",
#     "GCST008375",
#     "GCST008376",
#     "GCST008413",
#     "GCST008493",
#     "GCST008646",
#     "GCST008831",
#     "GCST008834",
#     "GCST008835",
#     "GCST008836",
#     "GCST008860",
#     "GCST008870",
#     "GCST008871",
#     "GCST008872",
#     "GCST008977",
#     "GCST009007",
#     "GCST009008",
#     "GCST009071",
#     "GCST009073",
#     "GCST009074",
#     "GCST009075",
#     "GCST009076",
#     "GCST009077",
#     "GCST009078",
#     "GCST009079",
#     "GCST009503",
#     "GCST009665",
#     "GCST009680",
#     "GCST009825",
#     "GCST009826",
#     "GCST009827",
#     "GCST009828",
#     "GCST009829",
#     "GCST009830",
#     "GCST009869",
#     "GCST009872",
#     "GCST009895",
#     "GCST009896",
#     "GCST009985",
#     "GCST010099",
#     "GCST010100",
#     "GCST010148",
#     "GCST010152",
#     "GCST010285",
#     "GCST010286",
#     "GCST010287",
#     "GCST010288",
#     "GCST010302",
#     "GCST010303",
#     "GCST010304",
#     "GCST010347",
#     "GCST010462",
#     "GCST010508",
#     "GCST010616",
#     "GCST010756",
#     "GCST010757",
#     "GCST010758",
#     "GCST010759",
#     "GCST010760",
#     "GCST010761",
#     "GCST010797",
#     "GCST010878",
#     "GCST010879",
#     "GCST010880",
#     "GCST010956",
#     "GCST010992",
#     "GCST011045",
#     "GCST011046",
#     "GCST011047",
#     "GCST011048",
#     "GCST011049",
#     "GCST011108",
#     "GCST011117",
#     "GCST011120",
#     "GCST011121",
#     "GCST011177",
#     "GCST011178",
#     "GCST011256",
#     "GCST011298",
#     "GCST011320",
#     "GCST011433",
#     "GCST011461",
#     "GCST011462",
#     "GCST011463",
#     "GCST011498",
#     "GCST011526",
#     "GCST011535",
#     "GCST011584",
#     "GCST011656",
#     "GCST011795",
#     "GCST011817",
#     "GCST011829",
#     "GCST011830",
#     "GCST011831",
#     "GCST011832",
#     "GCST011957",
#     "GCST011973",
#     "GCST011974",
#     "GCST012016",
#     "GCST012176",
#     "GCST012178",
#     "GCST012195",
#     "GCST012196",
#     "GCST012197",
#     "GCST012199",
#     "GCST012200",
#     "GCST012201",
#     "GCST012202",
#     "GCST012203",
#     "GCST012204",
#     "GCST012205",
#     "GCST012206",
#     "GCST012234",
#     "GCST012235",
#     "GCST012236",
#     "GCST012237",
#     "GCST012238",
#     "GCST012239",
#     "GCST012240",
#     "GCST012241",
#     "GCST012242",
#     "GCST012281",
#     "GCST012286",
#     "GCST012287",
#     "GCST012360",
#     "GCST012396",
#     "GCST012397",
#     "GCST012421",
#     "GCST012467",
#     "GCST012468",
#     "GCST012469",
#     "GCST012470",
#     "GCST012471",
#     "GCST012472",
#     "GCST012473",
#     "GCST012474",
#     "GCST012475",
#     "GCST012477",
#     "GCST012776",
#     "GCST012978",
#     "GCST012979",
#     "GCST90000032",
#     "GCST90002423",
#     "GCST90002424",
#     "GCST90002425",
#     "GCST90011804",
#     "GCST90011805",
#     "GCST90011806",
#     "GCST90011807",
#     "GCST90011808",
#     "GCST90011810",
#     "GCST90011811",
#     "GCST90011812",
#     "GCST90011813",
#     "GCST90011815",
#     "GCST90011816",
#     "GCST90011817",
#     "GCST90011818",
#     "GCST90011820",
#     "GCST90011821",
#     "GCST90011822",
#     "GCST90011823",
#     "GCST90011857",
#     "GCST90011858",
#     "GCST90012177",
#     "GCST90013410",
#     "GCST90013662",
#     "GCST90013694",
#     "GCST90013695",
#     "GCST90013696",
#     "GCST90013697",
#     "GCST90013698",
#     "GCST90013699",
#     "GCST90013700",
#     "GCST90013702",
#     "GCST90013703",
#     "GCST90013704",
#     "GCST90013705",
#     "GCST90013706",
#     "GCST90013736",
#     "GCST90013737",
#     "GCST90013738",
#     "GCST90013739",
#     "GCST90013741",
#     "GCST90013742",
#     "GCST90013743",
#     "GCST90013771",
#     "GCST90013772",
#     "GCST90013773",
#     "GCST90013774",
#     "GCST90013776",
#     "GCST90013777",
#     "GCST90013778",
#     "GCST90013862",
#     "GCST90013866",
#     "GCST90013867",
#     "GCST90014045",
#     "GCST90016665",
#     "GCST90018579",
#     "GCST90018583",
#     "GCST90018588",
#     "GCST90018597",
#     "GCST90018618",
#     "GCST90018621",
#     "GCST90018629",
#     "GCST90018655",
#     "GCST90018668",
#     "GCST90018673",
#     "GCST90018678",
#     "GCST90018685",
#     "GCST90018709",
#     "GCST90018799",
#     "GCST90018803",
#     "GCST90018808",
#     "GCST90018817",
#     "GCST90018838",
#     "GCST90018841",
#     "GCST90018849",
#     "GCST90018875",
#     "GCST90018888",
#     "GCST90018893",
#     "GCST90018898",
#     "GCST90018905",
#     "GCST90018929",
#     "GCST90020034",
#     "GCST90020035",
#     "GCST90020096",
#     "GCST90026461",
#     "GCST90026462",
#     "GCST90026463",
#     "GCST90026464",
#     "GCST90026465",
#     "GCST90026466",
#     "GCST90026467",
#     "GCST90026468",
#     "GCST90026469",
#     "GCST90026648",
#     "GCST90027051",
#     "GCST90027052",
#     "GCST90027054",
#     "GCST90027055",
#     "GCST90027056",
#     "GCST90027058",
#     "GCST90027059",
#     "GCST90027060",
#     "GCST90029042",
#     "GCST90029043",
#     "GCST90029044",
#     "GCST90029045",
#     "GCST90029046",
#     "GCST90029047",
#     "GCST90029048",
#     "GCST90029049",
#     "GCST90029050",
#     "GCST90029051",
#     "GCST90029052",
#     "GCST90029053",
#     "GCST90029054",
#     "GCST90029055",
#     "GCST90029056",
#     "GCST90029057",
#     "GCST90029058",
#     "GCST90029059",
#     "GCST90029060",
#     "GCST90029061",
#     "GCST90029062",
#     "GCST90029063",
#     "GCST90029064",
#     "GCST90029065",
#     "GCST90029066",
#     "GCST90041792",
#     "GCST90041793",
#     "GCST90041799",
#     "GCST90041800",
#     "GCST90041807",
#     "GCST90041812",
#     "GCST90041814",
#     "GCST90041816",
#     "GCST90041818",
#     "GCST90041819",
#     "GCST90041821",
#     "GCST90041822",
#     "GCST90041829",
#     "GCST90041834",
#     "GCST90041846",
#     "GCST90041847",
#     "GCST90041848",
#     "GCST90041851",
#     "GCST90041852",
#     "GCST90041853",
#     "GCST90041854",
#     "GCST90041855",
#     "GCST90041857",
#     "GCST90041858",
#     "GCST90041859",
#     "GCST90041862",
#     "GCST90041865",
#     "GCST90041867",
#     "GCST90041869",
#     "GCST90041873",
#     "GCST90041874",
#     "GCST90041875",
#     "GCST90041876",
#     "GCST90041877",
#     "GCST90041878",
#     "GCST90041880",
#     "GCST90041883",
#     "GCST90041885",
#     "GCST90041886",
#     "GCST90041887",
#     "GCST90041888",
#     "GCST90041891",
#     "GCST90041893",
#     "GCST90041894",
#     "GCST90041895",
#     "GCST90041896",
#     "GCST90041897",
#     "GCST90041901",
#     "GCST90041902",
#     "GCST90041903",
#     "GCST90041904",
#     "GCST90041905",
#     "GCST90041906",
#     "GCST90041909",
#     "GCST90041913",
#     "GCST90041915",
#     "GCST90041916",
#     "GCST90041917",
#     "GCST90041919",
#     "GCST90041920",
#     "GCST90041923",
#     "GCST90041924",
#     "GCST90042670",
#     "GCST90042673",
#     "GCST90042685",
#     "GCST90042696",
#     "GCST90042699",
#     "GCST90042758",
#     "GCST90042759",
#     "GCST90042760",
#     "GCST90042877",
#     "GCST90043628",
#     "GCST90043843",
#     "GCST90043846",
#     "GCST90043847",
#     "GCST90043848",
#     "GCST90043850",
#     "GCST90043851",
#     "GCST90043852",
#     "GCST90043853",
#     "GCST90043857",
#     "GCST90043858",
#     "GCST90043859",
#     "GCST90043860",
#     "GCST90043861",
#     "GCST90043863",
#     "GCST90043864",
#     "GCST90043865",
#     "GCST90043892",
#     "GCST90043894",
#     "GCST90043898",
#     "GCST90043902",
#     "GCST90043910",
#     "GCST90043912",
#     "GCST90043913",
#     "GCST90043914",
#     "GCST90043915",
#     "GCST90043920",
#     "GCST90043921",
#     "GCST90043922",
#     "GCST90043923",
#     "GCST90043924",
#     "GCST90043925",
#     "GCST90043927",
#     "GCST90043928",
#     "GCST90043929",
#     "GCST90043930",
#     "GCST90043931",
#     "GCST90043932",
#     "GCST90043933",
#     "GCST90043939",
#     "GCST90043941",
#     "GCST90043945",
#     "GCST90043946",
#     "GCST90043947",
#     "GCST90043948",
#     "GCST90054800",
#     "GCST90054801",
#     "GCST90054802",
#     "GCST90060090",
#     "GCST90061436",
#     "GCST90061437",
#     "GCST90061438",
#     "GCST90077626",
#     "GCST90077635",
#     "GCST90077640",
#     "GCST90078950",
#     "GCST90079100",
#     "GCST90079101",
#     "GCST90079107",
#     "GCST90079108",
#     "GCST90079139",
#     "GCST90079140",
#     "GCST90081612",
#     "GCST90081613",
#     "GCST90081614",
#     "GCST90081615",
#     "GCST90081617",
#     "GCST90081618",
#     "GCST90081619",
#     "GCST90081620",
#     "GCST90081621",
#     "GCST90081622",
#     "GCST90081625",
#     "GCST90081626",
#     "GCST90081627",
#     "GCST90081629",
#     "GCST90081630",
#     "GCST90082936",
#     "GCST90083065",
#     "GCST90083066",
#     "GCST90083067",
#     "GCST90083068",
#     "GCST90083069",
#     "GCST90083070",
#     "GCST90083074",
#     "GCST90083078",
#     "GCST90083079",
#     "GCST90083081",
#     "GCST90083082",
#     "GCST90083083",
#     "GCST90083086",
#     "GCST90083087",
#     "GCST90083093",
#     "GCST90083094",
#     "GCST90083095",
#     "GCST90083096",
#     "GCST90083099",
#     "GCST90083101",
#     "GCST90083102",
#     "GCST90083104",
#     "GCST90083108",
#     "GCST90083109",
#     "GCST90083113",
#     "GCST90083115",
#     "GCST90083116",
#     "GCST90083117",
#     "GCST90083118",
#     "GCST90083119",
#     "GCST90083120",
#     "GCST90083125",
#     "GCST90083126",
#     "GCST90083559",
#     "GCST90083561",
#     "GCST90083563",
#     "GCST90083564",
#     "GCST90083566",
#     "GCST90083567",
#     "GCST90083569",
#     "GCST90083571",
#     "GCST90083572",
#     "GCST90083573",
#     "GCST90083574",
#     "GCST90083575",
#     "GCST90083576",
#     "GCST90083579",
#     "GCST90083580",
#     "GCST90083588",
#     "GCST90083589",
#     "GCST90083590",
#     "GCST90083591",
#     "GCST90083592",
#     "GCST90083593",
#     "GCST90083594",
#     "GCST90083596",
#     "GCST90083597",
#     "GCST90083598",
#     "GCST90083601",
#     "GCST90083602",
#     "GCST90083603",
#     "GCST90083604",
#     "GCST90083605",
#     "GCST90083606",
#     "GCST90083607",
#     "GCST90083608",
#     "GCST90083609",
#     "GCST90083610",
#     "GCST90083611",
#     "GCST90083612",
#     "GCST90083613",
#     "GCST90083614",
#     "GCST90083615",
#     "GCST90083618",
#     "GCST90083625",
#     "GCST90083626",
#     "GCST90083631",
#     "GCST90083633",
#     "GCST90083634",
#     "GCST90083635",
#     "GCST90083636",
#     "GCST90085333",
#     "GCST90085334",
#     "GCST90085336",
#     "GCST90085337",
#     "GCST90085338",
#     "GCST90085339",
#     "GCST90085340",
#     "GCST90085699",
#     "GCST90085700",
#     "GCST90085701",
#     "GCST90086048",
#     "GCST90086050",
#     "GCST90086052",
#     "GCST90090980",
#     "GCST90091211",
#     "GCST90092003",
#     "GCST90093302",
#     "GCST90093303",
#     "GCST90094626",
#     "GCST90094652",
#     "GCST90094653",
#     "GCST90095079",
#     "GCST90095080",
#     "GCST90095126",
#     "GCST90095127",
#     "GCST90095128",
#     "GCST90096811",
#     "GCST90100588",
#     "GCST90101725",
#     "GCST90101893",
#     "GCST90101894",
#     "GCST90101895",
#     "GCST90101896",
#     "GCST90102289",
#     "GCST90102435",
#     "GCST90102436",
#     "GCST90102437",
#     "GCST90102438",
#     "GCST90102439",
#     "GCST90102440",
#     "GCST90102441",
#     "GCST90102456",
#     "GCST90102457",
#     "GCST90102458",
#     "GCST90102459",
#     "GCST90102510",
#     "GCST90103371",
#     "GCST90103971",
#     "GCST90104163",
#     "GCST90104177",
#     "GCST90104178",
#     "GCST90104489",
#     "GCST90104599",
#     "GCST90104600",
#     "GCST90104601",
#     "GCST90104602",
#     "GCST90104603",
#     "GCST90104604",
#     "GCST90104605",
#     "GCST90104606",
#     "GCST90104607",
#     "GCST90104608",
#     "GCST90104609",
#     "GCST90104610",
#     "GCST90104709",
#     "GCST90104804",
#     "GCST90104805",
#     "GCST90104810",
#     "GCST90104811",
#     "GCST90104812",
#     "GCST90104813",
#     "GCST90104894",
#     "GCST90104895",
#     "GCST90104896",
#     "GCST90105079",
#     "GCST90128460",
#     "GCST90128463",
#     "GCST90129576",
#     "GCST90129577",
#     "GCST90131430",
#     "GCST90132908",
#     "GCST90134420",
#     "GCST90134421",
#     "GCST90134422",
#     "GCST90134423",
#     "GCST90134567",
#     "GCST90134568",
#     "GCST90134569",
#     "GCST90134570",
#     "GCST90134571",
#     "GCST90134661",
#     "GCST90134662",
#     "GCST90134663",
#     "GCST90134664",
#     "GCST90137411",
#     "GCST90137412",
#     "GCST90140995",
#     "GCST90140997",
#     "GCST90140998",
#     "GCST90140999",
#     "GCST90141000",
#     "GCST90141001",
#     "GCST90141002",
#     "GCST90141004",
#     "GCST90141005",
#     "GCST90141006",
#     "GCST90141007",
#     "GCST90141008",
#     "GCST90141009",
#     "GCST90141011",
#     "GCST90141012",
#     "GCST90141014",
#     "GCST90141015",
#     "GCST90141016",
#     "GCST90141017",
#     "GCST90141018",
#     "GCST90141019",
#     "GCST90141021",
#     "GCST90141022",
#     "GCST90141023",
#     "GCST90141024",
#     "GCST90141025",
#     "GCST90141026",
#     "GCST90141028",
#     "GCST90162552",
#     "GCST90162555",
#     "GCST90179122",
#     "GCST90179123",
#     "GCST90179124",
#     "GCST90239710",
#     "GCST90239844",
#     "GCST90239845",
#     "GCST90239846",
#     "GCST90239847",
#     "GCST90243964",
#     "GCST90243993",
#     "GCST90243994",
#     "GCST90243995",
#     "GCST90243996",
#     "GCST90243997",
#     "GCST90243998",
#     "GCST90243999",
#     "GCST90244000",
#     "GCST90244001",
#     "GCST90244101",
#     "GCST90244167",
#     "GCST90244168",
#     "GCST90244553",
#     "GCST90245871",
#     "GCST90245873",
#     "GCST90245874",
#     "GCST90245887",
#     "GCST90245888",
#     "GCST90246023",
#     "GCST90246024",
#     "GCST90246026",
#     "GCST90246027",
#     "GCST90246028",
#     "GCST90246029",
#     "GCST90246030",
#     "GCST90246031",
#     "GCST90246033",
#     "GCST90246034",
#     "GCST90246035",
#     "GCST90246358",
#     "GCST90246359",
#     "GCST90250827",
#     "GCST90250828",
#     "GCST90250829",
#     "GCST90255396",
#     "GCST90255397",
#     "GCST90255398",
#     "GCST90255399",
#     "GCST90255400",
#     "GCST90255401",
#     "GCST90255402",
#     "GCST90255403",
#     "GCST90255404",
#     "GCST90255469",
#     "GCST90255470",
#     "GCST90255471",
#     "GCST90255472",
#     "GCST90255473",
#     "GCST90255474",
#     "GCST90255475",
#     "GCST90255499",
#     "GCST90255678",
#     "GCST90258656",
#     "GCST90258658",
#     "GCST90266933",
#     "GCST90267270",
#     "GCST90267271",
#     "GCST90267392",
#     "GCST90267393",
#     "GCST90267394",
#     "GCST90267395",
#     "GCST90267396",
#     "GCST90267397",
#     "GCST90267403",
#     "GCST90267995",
#     "GCST90267996",
#     "GCST90267997",
#     "GCST90267998",
#     "GCST90269956",
#     "GCST90269957",
#     "GCST90270342",
#     "GCST90270343",
#     "GCST90270344",
#     "GCST90271715",
#     "GCST90271955",
#     "GCST90271956",
#     "GCST90274713",
#     "GCST90274714",
#     "GCST90274715",
#     "GCST90274716",
#     "GCST90274717",
#     "GCST90274732",
#     "GCST90277434",
#     "GCST90296102",
#     "GCST90296471",
#     "GCST90296472",
#     "GCST90296481",
#     "GCST90296482",
#     "GCST90296485",
#     "GCST90296486",
#     "GCST90296487",
#     "GCST90296488",
#     "GCST90296489",
#     "GCST90296490",
#     "GCST90296491",
#     "GCST90296492",
#     "GCST90296493",
#     "GCST90296494",
#     "GCST90296495",
#     "GCST90296660",
#     "GCST90296661",
#     "GCST90296662",
#     "GCST90296663",
#     "GCST90296664",
#     "GCST90296665",
#     "GCST90296719",
#     "GCST90296720",
#     "GCST90296721",
#     "GCST90296722",
#     "GCST90296724",
#     "GCST90296725",
#     "GCST90296726",
#     "GCST90296727",
#     "GCST90296728",
#     "GCST90297546",
#     "GCST90297547",
#     "GCST90297562",
#     "GCST90297563",
#     "GCST90297588",
#     "GCST90297617",
#     "GCST90297618",
#     "GCST90297620",
#     "GCST90297642",
#     "GCST90297671",
#     "GCST90297673",
#     "GCST90297693",
#     "GCST90297718",
#     "GCST90297719",
#     "GCST90297722",
#     "GCST90297735",
#     "GCST90297765",
#     "GCST90297767",
#     "GCST90301329",
#     "GCST90308589",
#     "GCST90308750",
#     "GCST90308751",
#     "GCST90308752",
#     "GCST90308753",
#     "GCST90308754",
#     "GCST90308755",
#     "GCST90308756",
#     "GCST90308757",
#     "GCST90308758",
#     "GCST90308760",
#     "GCST90308761",
#     "GCST90308762",
#     "GCST90308763",
#     "GCST90308764",
#     "GCST90308765",
#     "GCST90308766",
#     "GCST90315948",
#     "GCST90319499",
#     "GCST90319500",
#     "GCST90319501",
#     "GCST90319677",
#     "GCST90319678",
#     "GCST90319679",
#     "GCST90319680",
#     "GCST90319681",
#     "GCST90319689",
#     "GCST90319844",
#     "GCST90319855",
#     "GCST90320046",
#     "GCST90320047",
#     "GCST90320048",
#     "GCST90320054",
#     "GCST90320055",
#     "GCST90320056",
#     "GCST90320057",
#     "GCST90320058",
#     "GCST90320059",
#     "GCST90320060",
#     "GCST90320061",
#     "GCST90320062",
#     "GCST90320063",
#     "GCST90320064",
#     "GCST90320065",
#     "GCST90321087",
#     "GCST90321088",
#     "GCST90321089",
#     "GCST90321104",
#     "GCST90321105",
#     "GCST90321106",
#     "GCST90321107",
#     "GCST90321108",
#     "GCST90321109",
#     "GCST90321110",
#     "GCST90321111",
#     "GCST90321112",
#     "GCST90321113",
#     "GCST90321114",
#     "GCST90321115",
#     "GCST90321116",
#     "GCST90321117",
#     "GCST90328132",
#     "GCST90328133",
#     "GCST90328134",
#     "GCST90328135",
#     "GCST90399469",
#     "GCST90399471",
#     "GCST90399472",
#     "GCST90399473",
#     "GCST90399474",
#     "GCST90399475",
#     "GCST90399476",
#     "GCST90399477",
#     "GCST90399736",
#     "GCST90399737",
#     "GCST90399738",
#     "GCST90399739",
#     "GCST90399740",
#     "GCST90428117",
#     "GCST90428118",
#     "GCST90428466",
#     "GCST90428467",
#     "GCST90428574",
#     "GCST90428859",
#     "GCST90428865",
#     "GCST90429846",
#     "GCST90429847",
#     "GCST90429848",
#     "GCST90432134",
#     "GCST90432138",
#     "GCST90432143",
#     "GCST90432144",
#     "GCST90432146",
#     "GCST90432150",
#     "GCST90432151",
#     "GCST90432160",
#     "GCST90432161",
#     "GCST90432162",
#     "GCST90432163",
#     "GCST90432164",
#     "GCST90435238",
#     "GCST90435239",
#     "GCST90435240",
#     "GCST90435241",
#     "GCST90435242",
#     "GCST90435243",
#     "GCST90435268",
#     "GCST90435438",
#     "GCST90435578",
#     "GCST90435584",
#     "GCST90435589",
#     "GCST90435590",
#     "GCST90435594",
#     "GCST90435595",
#     "GCST90435596",
#     "GCST90435600",
#     "GCST90435601",
#     "GCST90435602",
#     "GCST90435605",
#     "GCST90435606",
#     "GCST90435608",
#     "GCST90435609",
#     "GCST90435610",
#     "GCST90435611",
#     "GCST90435613",
#     "GCST90435615",
#     "GCST90435619",
#     "GCST90435620",
#     "GCST90435627",
#     "GCST90435630",
#     "GCST90435631",
#     "GCST90435632",
#     "GCST90435633",
#     "GCST90435634",
#     "GCST90435636",
#     "GCST90435643",
#     "GCST90446191",
#     "GCST90446192",
#     "GCST90446193",
#     "GCST90446194",
#     "GCST90446195",
#     "GCST90446196",
#     "GCST90446197",
#     "GCST90446198",
#     "GCST90446199",
#     "GCST90446200",
#     "GCST90446201",
#     "GCST90446202",
#     "GCST90446203",
#     "GCST90446204",
#     "GCST90446205",
#     "GCST90446206",
#     "GCST90446207",
#     "GCST90446208",
#     "GCST90446421",
#     "GCST90446422",
#     "GCST90446423",
#     "GCST90446424",
#     "GCST90446468",
#     "GCST90446469",
#     "GCST90446470",
#     "GCST90446471",
#     "GCST90446472",
#     "GCST90446473",
#     "GCST90446474",
#     "GCST90446487",
#     "GCST90447297",
#     "GCST90451657",
#     "GCST90454186",
#     "GCST90454202",
#     "GCST90454344",
#     "GCST90454345",
#     "GCST90454346",
#     "GCST90454347",
#     "GCST90454348",
#     "GCST90455518",
#     "GCST90455519",
#     "GCST90455520",
#     "GCST90455521",
#     "GCST90455522",
#     "GCST90455523",
#     "GCST90455524",
#     "GCST90455527",
#     "GCST90455528",
#     "GCST90455651",
#     "GCST90468114",
#     "GCST90468117",
#     "GCST90472804",
#     "GCST90473003",
#     "GCST90475169",
#     "GCST90475170",
#     "GCST90475180",
#     "GCST90475181",
#     "GCST90475182",
#     "GCST90475183",
#     "GCST90475184",
#     "GCST90475185",
#     "GCST90475186",
#     "GCST90475187",
#     "GCST90475188",
#     "GCST90475189",
#     "GCST90475190",
#     "GCST90475566",
#     "GCST90475567",
#     "GCST90475568",
#     "GCST90475569",
#     "GCST90475570",
#     "GCST90475571",
#     "GCST90475572",
#     "GCST90475573",
#     "GCST90475574",
#     "GCST90475575",
#     "GCST90475576",
#     "GCST90475577",
#     "GCST90475578",
#     "GCST90475581",
#     "GCST90475582",
#     "GCST90475583",
#     "GCST90475586",
#     "GCST90475587",
#     "GCST90475588",
#     "GCST90475589",
#     "GCST90475590",
#     "GCST90475591",
#     "GCST90475592",
#     "GCST90475593",
#     "GCST90475594",
#     "GCST90475595",
#     "GCST90475596",
#     "GCST90475597",
#     "GCST90475598",
#     "GCST90475599",
#     "GCST90475600",
#     "GCST90475603",
#     "GCST90475607",
#     "GCST90475608",
#     "GCST90475609",
#     "GCST90475610",
#     "GCST90475614",
#     "GCST90475615",
#     "GCST90476477",
#     "GCST90476478",
#     "GCST90476578",
#     "GCST90476579",
#     "GCST90476580",
#     "GCST90476582",
#     "GCST90476583",
#     "GCST90476584",
#     "GCST90476585",
#     "GCST90476586",
#     "GCST90477167",
#     "GCST90477168",
#     "GCST90477171",
#     "GCST90477173",
#     "GCST90477174",
#     "GCST90477175",
#     "GCST90477176",
#     "GCST90477177",
#     "GCST90477178",
#     "GCST90477179",
#     "GCST90477182",
#     "GCST90477183",
#     "GCST90477184",
#     "GCST90477185",
#     "GCST90477190",
#     "GCST90477191",
#     "GCST90477192",
#     "GCST90477196",
#     "GCST90477199",
#     "GCST90477200",
#     "GCST90477201",
#     "GCST90477202",
#     "GCST90477203",
#     "GCST90477206",
#     "GCST90477208",
#     "GCST90477209",
#     "GCST90477210",
#     "GCST90477211",
#     "GCST90477212",
#     "GCST90477213",
#     "GCST90477214",
#     "GCST90477215",
#     "GCST90477217",
#     "GCST90477218",
#     "GCST90477219",
#     "GCST90477220",
#     "GCST90477221",
#     "GCST90477222",
#     "GCST90477227",
#     "GCST90477228",
#     "GCST90477229",
#     "GCST90477230",
#     "GCST90477231",
#     "GCST90477232",
#     "GCST90477233",
#     "GCST90477234",
#     "GCST90477235",
#     "GCST90477236",
#     "GCST90477237",
#     "GCST90477238",
#     "GCST90477239",
#     "GCST90477240",
#     "GCST90477244",
#     "GCST90477245",
#     "GCST90477249",
#     "GCST90479527",
#     "GCST90479528",
#     "GCST90479532",
#     "GCST90479533",
#     "GCST90479534",
#     "GCST90479535",
#     "GCST90479536",
#     "GCST90479537",
#     "GCST90479538",
#     "GCST90479774",
#     "GCST90479775",
#     "GCST90479777",
#     "GCST90479778",
#     "GCST90479780",
#     "GCST90479781",
#     "GCST90479783",
#     "GCST90479784",
#     "GCST90479785",
#     "GCST90479786",
#     "GCST90479789",
#     "GCST90479790",
#     "GCST90479793",
#     "GCST90479794",
#     "GCST90479795",
#     "GCST90479796",
#     "GCST90479798",
#     "GCST90479800",
#     "GCST90479801",
#     "GCST90479802",
#     "GCST90479803",
#     "GCST90479804",
#     "GCST90479805",
#     "GCST90479806",
#     "GCST90479807",
#     "GCST90479808",
#     "GCST90479809",
#     "GCST90479810",
#     "GCST90479811",
#     "GCST90479812",
#     "GCST90479813",
#     "GCST90479814",
#     "GCST90479815",
#     "GCST90479818",
#     "GCST90479820",
#     "GCST90479821",
#     "GCST90479822",
#     "GCST90479823",
#     "GCST90479825",
#     "GCST90479826",
#     "GCST90479829",
#     "GCST90479832",
#     "GCST90479833",
#     "GCST90481032",
#     "GCST90481033",
#     "GCST90481034",
#     "GCST90481035",
#     "GCST90481038",
#     "GCST90481041",
#     "GCST90481145",
#     "GCST90481147",
#     "GCST90481150",
#     "GCST90481245",
#     "GCST90481246",
#     "GCST90481247",
#     "GCST90481248",
#     "GCST90481252",
#     "GCST90481253",
#     "GCST90481254",
#     "GCST90481255",
#     "GCST90481475",
#     "GCST90481476",
#     "GCST90481477",
#     "GCST90481478",
#     "GCST90481480",
#     "GCST90481482",
#     "GCST90481484",
#     "GCST90481485",
#     "GCST90481486",
#     "GCST90481488",
#     "GCST90481489",
#     "GCST90481491",
#     "GCST90481492",
#     "GCST90481494",
#     "GCST90481495",
#     "GCST90481496",
#     "GCST90481497",
#     "GCST90481498",
#     "GCST90481499",
#     "GCST90481500",
#     "GCST90481501",
#     "GCST90481504",
#     "GCST90481505",
#     "GCST90481507",
#     "GCST90481508",
#     "GCST90481509",
#     "GCST90481510",
#     "GCST90481511",
#     "GCST90481512",
#     "GCST90481513",
#     "GCST90481514",
#     "GCST90481515",
#     "GCST90481516",
#     "GCST90481517",
#     "GCST90481518",
#     "GCST90481519",
#     "GCST90481520",
#     "GCST90481521",
#     "GCST90481522",
#     "GCST90481525",
#     "GCST90481526",
#     "GCST90481528",
#     "GCST90481529",
#     "GCST90481530",
#     "GCST90481531",
#     "GCST90481532",
#     "GCST90481533",
#     "GCST90481535",
#     "GCST90481539",
#     "GCST90481545",
#     "GCST90481546",
#     "GCST90481547",
#     "GCST90481565",
#     "GCST90481670",
#     "GCST90482626",
#     "GCST90483377",
#     "GCST90502765",
#     "GCST90502766",
#     "GCST90502767",
#     "GCST90502768",
#     "GCST90502769",
#     "GCST90502810",
#     "GCST90502811",
#     "GCST90502812",
#     "GCST90502813",
#     "GCST90502814",
#     "GCST90502815",
#     "GCST90502816",
#     "GCST90502817",
#     "GCST90502818",
#     "GCST90502819",
#     "GCST90502820",
#     "GCST90502826",
#     "GCST90502827",
#     "GCST90502828",
#     "GCST90502829",
#     "GCST90502830",
#     "GCST90503118",
#     "GCST90503208",
#     "GCST90503274",
#     "GCST90503275",
#     "GCST90503276",
#     "GCST90503277",
#     "GCST90503278",
#     "GCST90503279",
#     "GCST90503487",
#     "GCST90503488",
#     "GCST90503489",
#     "GCST90504004",
#     "GCST90504005",
#     "GCST90504006",
#     "GCST90551892",
#     "GCST90551893",
#     "GCST90551894",
#     "GCST90551895",
#     "GCST90551896",
#     "GCST90551897",
#     "GCST90551898",
#     "GCST90554823",
#     "GCST90559273",
#     "GCST90559274",
#     "GCST90559275",
#     "GCST90559276",
#     "GCST90559277",
#     "GCST90565174",
#     "GCST90565175",
#     "GCST90565176",
#     "GCST90568461",
#     "GCST90568462",
#     "GCST90568463",
#     "GCST90568464",
#     "GCST90568465",
#     "GCST90568466",
#     "GCST90568467",
#     "GCST90570627",
#     "GCST90570628",
#     "GCST90570629",
#     "GCST90570630",
#     "GCST90570631",
#     "GCST90624114",
#     "GCST90624746",
#     "GCST90624747",
#     "GCST90624798",
#     "GCST90624799",
#     "GCST90624800",
#     "GCST90624802",
#     "GCST90624804",
#     "GCST90624805",
#     "GCST90624806",
#     "GCST90624807",
#     "GCST90624808",
#     "GCST90624809",
#     "GCST90624810",
#     "GCST90627760",
#     "GCST90627761",
#     "GCST90627762",
#     "GCST90627763",
#     "GCST90627764",
#     "GCST90627775",
#     "GCST90627776",
#     "GCST90651040",
#     "GCST90651041",
#     "GCST90651042",
#     "GCST90651043",
#     "GCST90651044",
#     "GCST90651045",
#     "GCST90651046",
#     "GCST90651047",
#     "GCST90651048",
#     "GCST90651050",
#     "GCST90651051",
#     "GCST90651052",
#     "GCST90651053",
#     "GCST90651054",
#     "GCST90651055",
#     "GCST90651056",
#     "GCST90651057",
#     "GCST90651058",
#     "GCST90651059",
#     "GCST90651060",
#     "GCST90651061",
#     "GCST90651062",
#     "GCST90651063",
#     "GCST90651065",
#     "GCST90651066",
#     "GCST90651067",
#     "GCST90651068",
#     "GCST90651069",
#     "GCST90651104",
#     "GCST90651105",
#     "GCST90651106",
#     "GCST90651148",
#     "GCST90651150",
#     "GCST90651151",
#     "GCST90651154",
#     "GCST90651165",
#     "GCST90651166",
#     "GCST90651188",
#     "GCST90651189",
#     "GCST90651191",
#     "GCST90651193",
#     "GCST90651195",
#     "GCST90651226",
#     "GCST90651227",
#     "GCST90651238",
#     "GCST90651240",
#     "GCST90651244",
#     "GCST90651246",
#     "GCST90651258",
#     "GCST90651266",
#     "GCST90651274",
#     "GCST90651280",
#     "GCST90651289",
#     "GCST90651317",
#     "GCST90651338",
#     "GCST90651360",
#     "GCST90651366",
#     "GCST90651374",
#     "GCST90651377",
#     "GCST90651404",
#     "GCST90651416",
#     "GCST90651474",
#     "GCST90651511",
#     "GCST90651512",
#     "GCST90651562",
#     "GCST90651572",
#     "GCST90651678",
#     "GCST90651688",
#     "GCST90651702",
#     "GCST90651703",
#     "GCST90651716",
#     "GCST90651759",
#     "GCST90651841",
#     "GCST90651847",
#     "GCST90651848",
#     "GCST90651859",
#     "GCST90651923",
#     "GCST90651976",
#     "GCST90651978",
#     "GCST90651979",
#     "GCST90651980",
#     "GCST90652024",
#     "GCST90652052",
#     "GCST90652064",
#     "GCST90652081",
#     "GCST90652111",
#     "GCST90652126",
#     "GCST90652194",
#     "GCST90652236",
#     "GCST90652494",
#     "GCST90652495",
#     "GCST90652496",
#     "GCST90652497",
#     "GCST90652533",
#     "GCST90652534",
#     "GCST90652535",
#     "GCST90672021",
#     "GCST90672022",
#     "GCST90693318",
#     "GCST90693319",
#     "GCST90693320",
#     "GCST90693321",
#     "GCST90693322",
#     "GCST90693323",
#     "GCST90693324",
#     "GCST90693325",
#     "GCST90693326",
#     "GCST90693327",
#     "GCST90693328",
#     "GCST90693329",
#     "GCST90693330",
#     "GCST90693331",
#     "GCST90693332",
#     "GCST90693333",
#     "GCST90693334",
#     "GCST90693335",
#     "GCST90693336",
#     "GCST90693337",
#     "GCST90693338",
#     "GCST90693339",
#     "GCST90693340",
#     "GCST90693341",
#     "GCST90693342",
#     "GCST90693343",
#     "GCST90693344",
#     "GCST90693345",
#     "GCST90693346",
#     "GCST90693347",
#     "GCST90693348",
#     "GCST90693349",
#     "GCST90693350",
#     "GCST90693351",
#     "GCST90693352",
#     "GCST90702470",
#     "GCST90702471",
#     "GCST90702483",
#     "GCST90702484",
#     "GCST90707271",
#     "GCST90707272",
#     "GCST90707273",
#     "GCST90707274",
#     "GCST90709777",
#     "GCST90709778",
#     "GCST90711137",
#     "GCST90728577",
#     "GCST90728578",
#     "GCST90809294",
#     "GCST90809295",
#     "GCST90809296",
#     "GCST90828131",
#     "GCST90832127",
#     "GCST90832128",
#     "gtex_ge_lcl_ensg00000003393",
#     "gtex_ge_lcl_ensg00000004534",
#     "gtex_ge_lcl_ensg00000005156",
#     "gtex_ge_lcl_ensg00000006282",
#     "gtex_ge_lcl_ensg00000006327",
#     "gtex_ge_lcl_ensg00000007341",
#     "gtex_ge_lcl_ensg00000008128",
#     "gtex_ge_lcl_ensg00000008838",
#     "gtex_ge_lcl_ensg00000010626",
#     "gtex_ge_lcl_ensg00000011295",
#     "gtex_ge_lcl_ensg00000011376",
#     "gtex_ge_lcl_ensg00000011478",
#     "gtex_ge_lcl_ensg00000013288",
#     "gtex_ge_lcl_ensg00000013374",
#     "gtex_ge_lcl_ensg00000013561",
#     "gtex_ge_lcl_ensg00000014164",
#     "gtex_ge_lcl_ensg00000018610",
#     "gtex_ge_lcl_ensg00000018699",
#     "gtex_ge_lcl_ensg00000020922",
#     "gtex_ge_lcl_ensg00000021355",
#     "gtex_ge_lcl_ensg00000022556",
#     "gtex_ge_lcl_ensg00000023228",
#     "gtex_ge_lcl_ensg00000025156",
#     "gtex_ge_lcl_ensg00000025772",
#     "gtex_ge_lcl_ensg00000028528",
#     "gtex_ge_lcl_ensg00000030110",
#     "gtex_ge_lcl_ensg00000031691",
#     "gtex_ge_lcl_ensg00000032742",
#     "gtex_ge_lcl_ensg00000033178",
#     "gtex_ge_lcl_ensg00000035499",
#     "gtex_ge_lcl_ensg00000036448",
#     "gtex_ge_lcl_ensg00000037474",
#     "gtex_ge_lcl_ensg00000037757",
#     "gtex_ge_lcl_ensg00000038002",
#     "gtex_ge_lcl_ensg00000038219",
#     "gtex_ge_lcl_ensg00000041802",
#     "gtex_ge_lcl_ensg00000043143",
#     "gtex_ge_lcl_ensg00000043514",
#     "gtex_ge_lcl_ensg00000046647",
#     "gtex_ge_lcl_ensg00000049167",
#     "gtex_ge_lcl_ensg00000049247",
#     "gtex_ge_lcl_ensg00000051596",
#     "gtex_ge_lcl_ensg00000051620",
#     "gtex_ge_lcl_ensg00000052749",
#     "gtex_ge_lcl_ensg00000054282",
#     "gtex_ge_lcl_ensg00000054983",
#     "gtex_ge_lcl_ensg00000056050",
#     "gtex_ge_lcl_ensg00000059122",
#     "gtex_ge_lcl_ensg00000059691",
#     "gtex_ge_lcl_ensg00000063854",
#     "gtex_ge_lcl_ensg00000063978",
#     "gtex_ge_lcl_ensg00000064201",
#     "gtex_ge_lcl_ensg00000064687",
#     "gtex_ge_lcl_ensg00000064886",
#     "gtex_ge_lcl_ensg00000065268",
#     "gtex_ge_lcl_ensg00000065457",
#     "gtex_ge_lcl_ensg00000066230",
#     "gtex_ge_lcl_ensg00000067141",
#     "gtex_ge_lcl_ensg00000067445",
#     "gtex_ge_lcl_ensg00000067533",
#     "gtex_ge_lcl_ensg00000068097",
#     "gtex_ge_lcl_ensg00000068305",
#     "gtex_ge_lcl_ensg00000069998",
#     "gtex_ge_lcl_ensg00000070444",
#     "gtex_ge_lcl_ensg00000070718",
#     "gtex_ge_lcl_ensg00000070961",
#     "gtex_ge_lcl_ensg00000071894",
#     "gtex_ge_lcl_ensg00000072210",
#     "gtex_ge_lcl_ensg00000072506",
#     "gtex_ge_lcl_ensg00000072756",
#     "gtex_ge_lcl_ensg00000073350",
#     "gtex_ge_lcl_ensg00000073464",
#     "gtex_ge_lcl_ensg00000073605",
#     "gtex_ge_lcl_ensg00000073969",
#     "gtex_ge_lcl_ensg00000074319",
#     "gtex_ge_lcl_ensg00000075234",
#     "gtex_ge_lcl_ensg00000075975",
#     "gtex_ge_lcl_ensg00000076067",
#     "gtex_ge_lcl_ensg00000076555",
#     "gtex_ge_lcl_ensg00000076650",
#     "gtex_ge_lcl_ensg00000076826",
#     "gtex_ge_lcl_ensg00000076924",
#     "gtex_ge_lcl_ensg00000076944",
#     "gtex_ge_lcl_ensg00000077097",
#     "gtex_ge_lcl_ensg00000078070",
#     "gtex_ge_lcl_ensg00000079263",
#     "gtex_ge_lcl_ensg00000079691",
#     "gtex_ge_lcl_ensg00000079785",
#     "gtex_ge_lcl_ensg00000080608",
#     "gtex_ge_lcl_ensg00000081791",
#     "gtex_ge_lcl_ensg00000083807",
#     "gtex_ge_lcl_ensg00000084072",
#     "gtex_ge_lcl_ensg00000085382",
#     "gtex_ge_lcl_ensg00000085721",
#     "gtex_ge_lcl_ensg00000085982",
#     "gtex_ge_lcl_ensg00000086232",
#     "gtex_ge_lcl_ensg00000086504",
#     "gtex_ge_lcl_ensg00000087299",
#     "gtex_ge_lcl_ensg00000087842",
#     "gtex_ge_lcl_ensg00000088808",
#     "onek1k_ge_nk_ensg00000035115",
#     "onek1k_ge_nk_ensg00000035687",
#     "onek1k_ge_nk_ensg00000036448",
#     "onek1k_ge_nk_ensg00000037474",
#     "onek1k_ge_nk_ensg00000038002",
#     "onek1k_ge_nk_ensg00000042832",
#     "onek1k_ge_nk_ensg00000046651",
#     "onek1k_ge_nk_ensg00000047056",
#     "onek1k_ge_nk_ensg00000047579",
#     "onek1k_ge_nk_ensg00000047644",
#     "onek1k_ge_nk_ensg00000047662",
#     "onek1k_ge_nk_ensg00000048740",
#     "onek1k_ge_nk_ensg00000049192",
#     "onek1k_ge_nk_ensg00000049247",
#     "onek1k_ge_nk_ensg00000049449",
#     "onek1k_ge_nk_ensg00000051523",
#     "onek1k_ge_nk_ensg00000051596",
#     "onek1k_ge_nk_ensg00000051620",
#     "onek1k_ge_nk_ensg00000051825",
#     "onek1k_ge_nk_ensg00000052126",
#     "onek1k_ge_nk_ensg00000052749",
#     "onek1k_ge_nk_ensg00000053524",
#     "onek1k_ge_nk_ensg00000054148",
#     "onek1k_ge_nk_ensg00000054282",
#     "onek1k_ge_nk_ensg00000054523",
#     "onek1k_ge_nk_ensg00000054793",
#     "onek1k_ge_nk_ensg00000055211",
#     "onek1k_ge_nk_ensg00000056558",
#     "onek1k_ge_nk_ensg00000057252",
#     "onek1k_ge_nk_ensg00000057608",
#     "onek1k_ge_nk_ensg00000058063",
#     "onek1k_ge_nk_ensg00000058453",
#     "onek1k_ge_nk_ensg00000061987",
#     "onek1k_ge_nk_ensg00000063854",
#     "onek1k_ge_nk_ensg00000064201",
#     "onek1k_ge_nk_ensg00000064666",
#     "onek1k_ge_nk_ensg00000064763"
#   ]
# }

# ---

query targets($eids: [String!]!) {
    targets(ensemblIds: $eids) {
        total
        items {
            id
        }
    }
}

# {
#   "eids": [
#     "ENSG00000243244",
#     "ENSG00000172031",
#     "ENSG00000174527",
#     "ENSG00000260296",
#     "ENSG00000066468",
#     "ENSG00000163565",
#     "ENSG00000177076",
#     "ENSG00000106004",
#     "ENSG00000106299",
#     "ENSG00000069764",
#     "ENSG00000132323",
#     "ENSG00000068078",
#     "ENSG00000204482",
#     "ENSG00000235584",
#     "ENSG00000138180",
#     "ENSG00000117143",
#     "ENSG00000269821",
#     "ENSG00000110324",
#     "ENSG00000188177",
#     "ENSG00000118307",
#     "ENSG00000170209",
#     "ENSG00000096433",
#     "ENSG00000165556",
#     "ENSG00000115604",
#     "ENSG00000099365",
#     "ENSG00000161544",
#     "ENSG00000102910",
#     "ENSG00000153956",
#     "ENSG00000189184",
#     "ENSG00000124813",
#     "ENSG00000204610",
#     "ENSG00000136827",
#     "ENSG00000118785",
#     "ENSG00000140543",
#     "ENSG00000273132",
#     "ENSG00000198918",
#     "ENSG00000141968",
#     "ENSG00000139410",
#     "ENSG00000143842",
#     "ENSG00000179583",
#     "ENSG00000162521",
#     "ENSG00000186081",
#     "ENSG00000136045",
#     "ENSG00000198597",
#     "ENSG00000144820",
#     "ENSG00000112837",
#     "ENSG00000124222",
#     "ENSG00000142347",
#     "ENSG00000174099",
#     "ENSG00000112425",
#     "ENSG00000116857",
#     "ENSG00000099795",
#     "ENSG00000173402",
#     "ENSG00000101439",
#     "ENSG00000129534",
#     "ENSG00000177556",
#     "ENSG00000143196",
#     "ENSG00000151725",
#     "ENSG00000197170",
#     "ENSG00000118432",
#     "ENSG00000108423",
#     "ENSG00000185267",
#     "ENSG00000255974",
#     "ENSG00000120885",
#     "ENSG00000125835",
#     "ENSG00000262484",
#     "ENSG00000173281",
#     "ENSG00000233608",
#     "ENSG00000129450",
#     "ENSG00000167900",
#     "ENSG00000167755",
#     "ENSG00000102882",
#     "ENSG00000278192",
#     "ENSG00000116016",
#     "ENSG00000100906",
#     "ENSG00000135063",
#     "ENSG00000250641",
#     "ENSG00000204371",
#     "ENSG00000135413",
#     "ENSG00000124491",
#     "ENSG00000172215",
#     "ENSG00000150681",
#     "ENSG00000211895",
#     "ENSG00000204928",
#     "ENSG00000100883",
#     "ENSG00000168404",
#     "ENSG00000117425",
#     "ENSG00000171855",
#     "ENSG00000119401",
#     "ENSG00000228083",
#     "ENSG00000111640",
#     "ENSG00000117400",
#     "ENSG00000280119",
#     "ENSG00000135486",
#     "ENSG00000196092",
#     "ENSG00000143921",
#     "ENSG00000206077",
#     "ENSG00000136026",
#     "ENSG00000163519",
#     "ENSG00000120053",
#     "ENSG00000132950",
#     "ENSG00000171109",
#     "ENSG00000161031",
#     "ENSG00000275718",
#     "ENSG00000005339",
#     "ENSG00000133048",
#     "ENSG00000188293",
#     "ENSG00000167191",
#     "ENSG00000160161",
#     "ENSG00000253746",
#     "ENSG00000104325",
#     "ENSG00000164400",
#     "ENSG00000170835",
#     "ENSG00000109084",
#     "ENSG00000170949",
#     "ENSG00000198001",
#     "ENSG00000141433",
#     "ENSG00000088305",
#     "ENSG00000013583",
#     "ENSG00000143126",
#     "ENSG00000104267",
#     "ENSG00000103479",
#     "ENSG00000154316",
#     "ENSG00000030110",
#     "ENSG00000105427",
#     "ENSG00000112320",
#     "ENSG00000204542",
#     "ENSG00000164920",
#     "ENSG00000197496",
#     "ENSG00000136261",
#     "ENSG00000165807",
#     "ENSG00000213171",
#     "ENSG00000184515",
#     "ENSG00000165410",
#     "ENSG00000139547",
#     "ENSG00000145050",
#     "ENSG00000196415",
#     "ENSG00000160999",
#     "ENSG00000142494",
#     "ENSG00000169410",
#     "ENSG00000168078",
#     "ENSG00000178279",
#     "ENSG00000163710",
#     "ENSG00000147065",
#     "ENSG00000273604",
#     "ENSG00000121152",
#     "ENSG00000137076",
#     "ENSG00000100376",
#     "ENSG00000145996",
#     "ENSG00000092098",
#     "ENSG00000222009",
#     "ENSG00000131759",
#     "ENSG00000152556",
#     "ENSG00000144908",
#     "ENSG00000132330",
#     "ENSG00000073756",
#     "ENSG00000134760",
#     "ENSG00000147883",
#     "ENSG00000167085",
#     "ENSG00000137807",
#     "ENSG00000160188",
#     "ENSG00000121351",
#     "ENSG00000176566",
#     "ENSG00000075643",
#     "ENSG00000179526",
#     "ENSG00000114686",
#     "ENSG00000150593",
#     "ENSG00000176083",
#     "ENSG00000115271",
#     "ENSG00000155850",
#     "ENSG00000144026",
#     "ENSG00000169344",
#     "ENSG00000100979",
#     "ENSG00000157637",
#     "ENSG00000124102",
#     "ENSG00000198420",
#     "ENSG00000094963",
#     "ENSG00000188257",
#     "ENSG00000116288",
#     "ENSG00000101639",
#     "ENSG00000186687",
#     "ENSG00000216490",
#     "ENSG00000125398",
#     "ENSG00000108100",
#     "ENSG00000140379",
#     "ENSG00000162511",
#     "ENSG00000182944",
#     "ENSG00000164256",
#     "ENSG00000041515",
#     "ENSG00000136869",
#     "ENSG00000105668",
#     "ENSG00000204580",
#     "ENSG00000055130",
#     "ENSG00000175336",
#     "ENSG00000177666",
#     "ENSG00000114023",
#     "ENSG00000135446",
#     "ENSG00000143772",
#     "ENSG00000138311",
#     "ENSG00000100749",
#     "ENSG00000197405",
#     "ENSG00000158402",
#     "ENSG00000138741",
#     "ENSG00000133321",
#     "ENSG00000116977",
#     "ENSG00000112685",
#     "ENSG00000106648",
#     "ENSG00000177291",
#     "ENSG00000154920",
#     "ENSG00000261609",
#     "ENSG00000168539",
#     "ENSG00000241106",
#     "ENSG00000163823",
#     "ENSG00000134470",
#     "ENSG00000138670",
#     "ENSG00000116661",
#     "ENSG00000100344",
#     "ENSG00000181915",
#     "ENSG00000165006",
#     "ENSG00000134690",
#     "ENSG00000115594",
#     "ENSG00000134825",
#     "ENSG00000122025",
#     "ENSG00000251076",
#     "ENSG00000101346",
#     "ENSG00000174720",
#     "ENSG00000166869",
#     "ENSG00000100804",
#     "ENSG00000116199",
#     "ENSG00000198939",
#     "ENSG00000246705",
#     "ENSG00000164619",
#     "ENSG00000161395",
#     "ENSG00000151715",
#     "ENSG00000138814",
#     "ENSG00000137801",
#     "ENSG00000196569",
#     "ENSG00000138135",
#     "ENSG00000143954",
#     "ENSG00000147003",
#     "ENSG00000229590",
#     "ENSG00000248801",
#     "ENSG00000117114",
#     "ENSG00000104537",
#     "ENSG00000068724",
#     "ENSG00000221818",
#     "ENSG00000109861",
#     "ENSG00000168542",
#     "ENSG00000178035",
#     "ENSG00000181036",
#     "ENSG00000163735",
#     "ENSG00000141469",
#     "ENSG00000134852",
#     "ENSG00000277161",
#     "ENSG00000080644",
#     "ENSG00000136521",
#     "ENSG00000185338",
#     "ENSG00000257700",
#     "ENSG00000137675",
#     "ENSG00000112559",
#     "ENSG00000187486",
#     "ENSG00000120899",
#     "ENSG00000105287",
#     "ENSG00000141524",
#     "ENSG00000069974",
#     "ENSG00000253305",
#     "ENSG00000109519",
#     "ENSG00000143198",
#     "ENSG00000133315",
#     "ENSG00000165646",
#     "ENSG00000104964",
#     "ENSG00000100288",
#     "ENSG00000157330",
#     "ENSG00000034152",
#     "ENSG00000185811",
#     "ENSG00000213977",
#     "ENSG00000068366",
#     "ENSG00000074803",
#     "ENSG00000135766",
#     "ENSG00000170315",
#     "ENSG00000072571",
#     "ENSG00000116824",
#     "ENSG00000168004",
#     "ENSG00000111727",
#     "ENSG00000235173",
#     "ENSG00000196230",
#     "ENSG00000103740",
#     "ENSG00000128310",
#     "ENSG00000160584",
#     "ENSG00000172732",
#     "ENSG00000183246",
#     "ENSG00000185591",
#     "ENSG00000138166",
#     "ENSG00000124920",
#     "ENSG00000111801",
#     "ENSG00000132514",
#     "ENSG00000131471",
#     "ENSG00000242808",
#     "ENSG00000108773",
#     "ENSG00000267496",
#     "ENSG00000215018",
#     "ENSG00000165215",
#     "ENSG00000108848",
#     "ENSG00000231999",
#     "ENSG00000047597",
#     "ENSG00000131748",
#     "ENSG00000183542",
#     "ENSG00000007038",
#     "ENSG00000197822",
#     "ENSG00000040933",
#     "ENSG00000089685",
#     "ENSG00000105486",
#     "ENSG00000177182",
#     "ENSG00000172159",
#     "ENSG00000259153",
#     "ENSG00000158158",
#     "ENSG00000175063",
#     "ENSG00000231402",
#     "ENSG00000276045",
#     "ENSG00000239268",
#     "ENSG00000090382",
#     "ENSG00000162704",
#     "ENSG00000135925",
#     "ENSG00000134259",
#     "ENSG00000213221",
#     "ENSG00000008196",
#     "ENSG00000131845",
#     "ENSG00000137745",
#     "ENSG00000186104",
#     "ENSG00000013441",
#     "ENSG00000100519",
#     "ENSG00000130560",
#     "ENSG00000198015",
#     "ENSG00000105708",
#     "ENSG00000100342",
#     "ENSG00000048162",
#     "ENSG00000172901",
#     "ENSG00000096717",
#     "ENSG00000176170",
#     "ENSG00000092345",
#     "ENSG00000026025",
#     "ENSG00000280099",
#     "ENSG00000221880",
#     "ENSG00000137070",
#     "ENSG00000113212",
#     "ENSG00000065882",
#     "ENSG00000173641",
#     "ENSG00000105229",
#     "ENSG00000049249",
#     "ENSG00000119938",
#     "ENSG00000188056",
#     "ENSG00000075213",
#     "ENSG00000064601",
#     "ENSG00000163297",
#     "ENSG00000070669",
#     "ENSG00000147872",
#     "ENSG00000136485",
#     "ENSG00000168961",
#     "ENSG00000160307",
#     "ENSG00000120949",
#     "ENSG00000100796",
#     "ENSG00000176476",
#     "ENSG00000137033",
#     "ENSG00000074966",
#     "ENSG00000144837",
#     "ENSG00000166828",
#     "ENSG00000186470",
#     "ENSG00000149451",
#     "ENSG00000198286",
#     "ENSG00000080493",
#     "ENSG00000253161",
#     "ENSG00000204518",
#     "ENSG00000173369",
#     "ENSG00000235663",
#     "ENSG00000205592",
#     "ENSG00000145107",
#     "ENSG00000133710",
#     "ENSG00000151474",
#     "ENSG00000144668",
#     "ENSG00000187912",
#     "ENSG00000197114",
#     "ENSG00000161980",
#     "ENSG00000104870",
#     "ENSG00000138162",
#     "ENSG00000188910",
#     "ENSG00000159592",
#     "ENSG00000257017",
#     "ENSG00000179091",
#     "ENSG00000125733",
#     "ENSG00000229847",
#     "ENSG00000154783",
#     "ENSG00000155657",
#     "ENSG00000110801",
#     "ENSG00000186832",
#     "ENSG00000132357",
#     "ENSG00000166432",
#     "ENSG00000170370",
#     "ENSG00000175305",
#     "ENSG00000259207",
#     "ENSG00000102245",
#     "ENSG00000062716",
#     "ENSG00000150551",
#     "ENSG00000185238",
#     "ENSG00000102901",
#     "ENSG00000173113",
#     "ENSG00000165806",
#     "ENSG00000115425",
#     "ENSG00000171314",
#     "ENSG00000113575",
#     "ENSG00000105538",
#     "ENSG00000155066",
#     "ENSG00000278709",
#     "ENSG00000176463",
#     "ENSG00000232593",
#     "ENSG00000138780",
#     "ENSG00000173085",
#     "ENSG00000166710",
#     "ENSG00000085563",
#     "ENSG00000171346",
#     "ENSG00000189067",
#     "ENSG00000158710",
#     "ENSG00000101365",
#     "ENSG00000242125",
#     "ENSG00000228278",
#     "ENSG00000057657",
#     "ENSG00000165264",
#     "ENSG00000263753",
#     "ENSG00000116266",
#     "ENSG00000265203",
#     "ENSG00000134851",
#     "ENSG00000257335",
#     "ENSG00000163558",
#     "ENSG00000164850",
#     "ENSG00000090612",
#     "ENSG00000101417",
#     "ENSG00000104427",
#     "ENSG00000112115",
#     "ENSG00000147421",
#     "ENSG00000185499",
#     "ENSG00000180543",
#     "ENSG00000144868",
#     "ENSG00000188486",
#     "ENSG00000131711",
#     "ENSG00000144648",
#     "ENSG00000127616",
#     "ENSG00000110321",
#     "ENSG00000180155",
#     "ENSG00000187840",
#     "ENSG00000081019",
#     "ENSG00000172818",
#     "ENSG00000156860",
#     "ENSG00000099910",
#     "ENSG00000124749",
#     "ENSG00000204936",
#     "ENSG00000240403",
#     "ENSG00000154529",
#     "ENSG00000183486",
#     "ENSG00000196689",
#     "ENSG00000182782",
#     "ENSG00000154451",
#     "ENSG00000077150",
#     "ENSG00000160613",
#     "ENSG00000143727",
#     "ENSG00000170017",
#     "ENSG00000010282",
#     "ENSG00000160117",
#     "ENSG00000107736",
#     "ENSG00000148943",
#     "ENSG00000174343",
#     "ENSG00000172673",
#     "ENSG00000141232",
#     "ENSG00000173200",
#     "ENSG00000140044",
#     "ENSG00000145431",
#     "ENSG00000139880",
#     "ENSG00000115956",
#     "ENSG00000173334",
#     "ENSG00000163017",
#     "ENSG00000149657",
#     "ENSG00000146410",
#     "ENSG00000152253",
#     "ENSG00000198851",
#     "ENSG00000169564",
#     "ENSG00000164309",
#     "ENSG00000184574",
#     "ENSG00000074047",
#     "ENSG00000149948",
#     "ENSG00000109332",
#     "ENSG00000095777",
#     "ENSG00000245848",
#     "ENSG00000198363",
#     "ENSG00000164089",
#     "ENSG00000148935",
#     "ENSG00000136514",
#     "ENSG00000173163",
#     "ENSG00000198523",
#     "ENSG00000170948",
#     "ENSG00000137727",
#     "ENSG00000227619",
#     "ENSG00000110169",
#     "ENSG00000176422",
#     "ENSG00000140545",
#     "ENSG00000100330",
#     "ENSG00000106397",
#     "ENSG00000164683",
#     "ENSG00000106078",
#     "ENSG00000109458",
#     "ENSG00000178752",
#     "ENSG00000088827",
#     "ENSG00000198961",
#     "ENSG00000137871",
#     "ENSG00000117707",
#     "ENSG00000022267",
#     "ENSG00000251605",
#     "ENSG00000198752",
#     "ENSG00000164659",
#     "ENSG00000112658",
#     "ENSG00000079841",
#     "ENSG00000163736",
#     "ENSG00000137869",
#     "ENSG00000144810",
#     "ENSG00000220201",
#     "ENSG00000128573",
#     "ENSG00000118096",
#     "ENSG00000164330",
#     "ENSG00000100503",
#     "ENSG00000165548",
#     "ENSG00000149929",
#     "ENSG00000198911",
#     "ENSG00000102225",
#     "ENSG00000107447",
#     "ENSG00000143850",
#     "ENSG00000106804",
#     "ENSG00000023608",
#     "ENSG00000145287",
#     "ENSG00000177301",
#     "ENSG00000174951",
#     "ENSG00000130816",
#     "ENSG00000159692",
#     "ENSG00000164236",
#     "ENSG00000243550",
#     "ENSG00000196557",
#     "ENSG00000124493",
#     "ENSG00000120659",
#     "ENSG00000182077",
#     "ENSG00000184986",
#     "ENSG00000130164",
#     "ENSG00000170549",
#     "ENSG00000179915",
#     "ENSG00000118596",
#     "ENSG00000166863",
#     "ENSG00000101182",
#     "ENSG00000108010",
#     "ENSG00000141756",
#     "ENSG00000181104",
#     "ENSG00000066336",
#     "ENSG00000108055",
#     "ENSG00000070614",
#     "ENSG00000281103",
#     "ENSG00000166441",
#     "ENSG00000138678",
#     "ENSG00000162747",
#     "ENSG00000119725",
#     "ENSG00000157873",
#     "ENSG00000169398",
#     "ENSG00000120875",
#     "ENSG00000138109",
#     "ENSG00000258689",
#     "ENSG00000204538",
#     "ENSG00000115009",
#     "ENSG00000229150",
#     "ENSG00000185624",
#     "ENSG00000119686",
#     "ENSG00000169248",
#     "ENSG00000038002",
#     "ENSG00000139618",
#     "ENSG00000231389",
#     "ENSG00000185610",
#     "ENSG00000166333",
#     "ENSG00000131374",
#     "ENSG00000164197",
#     "ENSG00000066044",
#     "ENSG00000126456",
#     "ENSG00000108518",
#     "ENSG00000147509",
#     "ENSG00000278540",
#     "ENSG00000116670",
#     "ENSG00000158050",
#     "ENSG00000232119",
#     "ENSG00000175535",
#     "ENSG00000188729",
#     "ENSG00000204361",
#     "ENSG00000124523",
#     "ENSG00000088726",
#     "ENSG00000183386",
#     "ENSG00000173175",
#     "ENSG00000136810",
#     "ENSG00000188124",
#     "ENSG00000214413",
#     "ENSG00000169967",
#     "ENSG00000160293",
#     "ENSG00000099949",
#     "ENSG00000037280",
#     "ENSG00000070950",
#     "ENSG00000275572",
#     "ENSG00000166183",
#     "ENSG00000168811",
#     "ENSG00000144182",
#     "ENSG00000197635",
#     "ENSG00000176293",
#     "ENSG00000158470",
#     "ENSG00000154832",
#     "ENSG00000136068",
#     "ENSG00000149090",
#     "ENSG00000104499",
#     "ENSG00000141447",
#     "ENSG00000168036",
#     "ENSG00000175646",
#     "ENSG00000068024",
#     "ENSG00000157219",
#     "ENSG00000049656",
#     "ENSG00000224863",
#     "ENSG00000076003",
#     "ENSG00000103145",
#     "ENSG00000277791",
#     "ENSG00000232629",
#     "ENSG00000187017",
#     "ENSG00000147121",
#     "ENSG00000132031",
#     "ENSG00000185668",
#     "ENSG00000057663",
#     "ENSG00000063046",
#     "ENSG00000156284",
#     "ENSG00000058085",
#     "ENSG00000181617",
#     "ENSG00000198933",
#     "ENSG00000136928",
#     "ENSG00000182481",
#     "ENSG00000086696",
#     "ENSG00000161267",
#     "ENSG00000242612",
#     "ENSG00000141905",
#     "ENSG00000069122",
#     "ENSG00000151690",
#     "ENSG00000239732",
#     "ENSG00000065621",
#     "ENSG00000133195",
#     "ENSG00000260955",
#     "ENSG00000131042",
#     "ENSG00000262877",
#     "ENSG00000185532",
#     "ENSG00000152348",
#     "ENSG00000142192",
#     "ENSG00000179604",
#     "ENSG00000253782",
#     "ENSG00000086548",
#     "ENSG00000108405",
#     "ENSG00000078246",
#     "ENSG00000157554",
#     "ENSG00000254043",
#     "ENSG00000164308",
#     "ENSG00000148334",
#     "ENSG00000187048",
#     "ENSG00000066027",
#     "ENSG00000145604",
#     "ENSG00000064205",
#     "ENSG00000130119",
#     "ENSG00000136840",
#     "ENSG00000233232",
#     "ENSG00000127083",
#     "ENSG00000148400",
#     "ENSG00000128335",
#     "ENSG00000159921",
#     "ENSG00000123178",
#     "ENSG00000198055",
#     "ENSG00000197442",
#     "ENSG00000134308",
#     "ENSG00000100739",
#     "ENSG00000123146",
#     "ENSG00000115468",
#     "ENSG00000075673",
#     "ENSG00000018625",
#     "ENSG00000185467",
#     "ENSG00000116194",
#     "ENSG00000130382",
#     "ENSG00000159958",
#     "ENSG00000168398",
#     "ENSG00000143226",
#     "ENSG00000196139",
#     "ENSG00000126067",
#     "ENSG00000203760",
#     "ENSG00000168702",
#     "ENSG00000110492",
#     "ENSG00000067225",
#     "ENSG00000260455",
#     "ENSG00000166147",
#     "ENSG00000168874",
#     "ENSG00000170558",
#     "ENSG00000104783",
#     "ENSG00000170477",
#     "ENSG00000169504",
#     "ENSG00000131018",
#     "ENSG00000260325",
#     "ENSG00000106211",
#     "ENSG00000102962",
#     "ENSG00000102683",
#     "ENSG00000087074",
#     "ENSG00000091136",
#     "ENSG00000188312",
#     "ENSG00000132854",
#     "ENSG00000119720",
#     "ENSG00000169507",
#     "ENSG00000133488",
#     "ENSG00000149212",
#     "ENSG00000163734",
#     "ENSG00000187554",
#     "ENSG00000129214",
#     "ENSG00000167207",
#     "ENSG00000145700",
#     "ENSG00000006555",
#     "ENSG00000204713",
#     "ENSG00000257989",
#     "ENSG00000167617",
#     "ENSG00000178252",
#     "ENSG00000033800",
#     "ENSG00000103528",
#     "ENSG00000140279",
#     "ENSG00000154096",
#     "ENSG00000100368",
#     "ENSG00000188581",
#     "ENSG00000167815",
#     "ENSG00000105329",
#     "ENSG00000274391",
#     "ENSG00000107566",
#     "ENSG00000196781",
#     "ENSG00000095637",
#     "ENSG00000157540",
#     "ENSG00000131969",
#     "ENSG00000101444",
#     "ENSG00000105426",
#     "ENSG00000108242",
#     "ENSG00000005022",
#     "ENSG00000164265",
#     "ENSG00000088325",
#     "ENSG00000065802",
#     "ENSG00000115993",
#     "ENSG00000108576",
#     "ENSG00000102977",
#     "ENSG00000166224",
#     "ENSG00000125571",
#     "ENSG00000169851",
#     "ENSG00000161634",
#     "ENSG00000143278",
#     "ENSG00000104936",
#     "ENSG00000100030",
#     "ENSG00000276644",
#     "ENSG00000127415",
#     "ENSG00000071655",
#     "ENSG00000139508",
#     "ENSG00000240871",
#     "ENSG00000123739",
#     "ENSG00000167978",
#     "ENSG00000188393",
#     "ENSG00000147684",
#     "ENSG00000204469",
#     "ENSG00000151014",
#     "ENSG00000157601",
#     "ENSG00000178078",
#     "ENSG00000121440",
#     "ENSG00000154380",
#     "ENSG00000146374",
#     "ENSG00000163209",
#     "ENSG00000105397",
#     "ENSG00000087510",
#     "ENSG00000132376",
#     "ENSG00000105976",
#     "ENSG00000160181",
#     "ENSG00000088812",
#     "ENSG00000175287",
#     "ENSG00000123353",
#     "ENSG00000168062",
#     "ENSG00000189377",
#     "ENSG00000196663",
#     "ENSG00000177283",
#     "ENSG00000235097",
#     "ENSG00000154556",
#     "ENSG00000134716",
#     "ENSG00000171940",
#     "ENSG00000128591",
#     "ENSG00000140105",
#     "ENSG00000149532",
#     "ENSG00000111275",
#     "ENSG00000099260",
#     "ENSG00000058404",
#     "ENSG00000255819",
#     "ENSG00000176014",
#     "ENSG00000124767",
#     "ENSG00000062096",
#     "ENSG00000184451",
#     "ENSG00000204706",
#     "ENSG00000205639",
#     "ENSG00000143612",
#     "ENSG00000166090",
#     "ENSG00000100097",
#     "ENSG00000189013",
#     "ENSG00000171680",
#     "ENSG00000085377",
#     "ENSG00000197561",
#     "ENSG00000076351",
#     "ENSG00000170439",
#     "ENSG00000110442",
#     "ENSG00000169860",
#     "ENSG00000110076",
#     "ENSG00000185222",
#     "ENSG00000163221",
#     "ENSG00000163106",
#     "ENSG00000113810",
#     "ENSG00000100767",
#     "ENSG00000044574",
#     "ENSG00000117650",
#     "ENSG00000116031",
#     "ENSG00000147416",
#     "ENSG00000155660",
#     "ENSG00000113594",
#     "ENSG00000130429",
#     "ENSG00000164736",
#     "ENSG00000253958",
#     "ENSG00000165819",
#     "ENSG00000120280",
#     "ENSG00000166592",
#     "ENSG00000173681",
#     "ENSG00000258279",
#     "ENSG00000134460",
#     "ENSG00000101986",
#     "ENSG00000253595",
#     "ENSG00000157933",
#     "ENSG00000104332",
#     "ENSG00000048540",
#     "ENSG00000132356",
#     "ENSG00000143942",
#     "ENSG00000129351",
#     "ENSG00000111665",
#     "ENSG00000094796",
#     "ENSG00000171126",
#     "ENSG00000214274",
#     "ENSG00000172650",
#     "ENSG00000169432",
#     "ENSG00000144619",
#     "ENSG00000173559",
#     "ENSG00000153283",
#     "ENSG00000112530",
#     "ENSG00000134548",
#     "ENSG00000124157",
#     "ENSG00000081665",
#     "ENSG00000167371",
#     "ENSG00000067082",
#     "ENSG00000071991",
#     "ENSG00000111331",
#     "ENSG00000135541",
#     "ENSG00000115353",
#     "ENSG00000162817",
#     "ENSG00000140600",
#     "ENSG00000165810",
#     "ENSG00000146592",
#     "ENSG00000100297",
#     "ENSG00000156475",
#     "ENSG00000143502",
#     "ENSG00000125633",
#     "ENSG00000154767",
#     "ENSG00000269954",
#     "ENSG00000154188",
#     "ENSG00000122707",
#     "ENSG00000144369",
#     "ENSG00000113460",
#     "ENSG00000143819",
#     "ENSG00000166527",
#     "ENSG00000148053",
#     "ENSG00000019582",
#     "ENSG00000085662",
#     "ENSG00000173947",
#     "ENSG00000182393",
#     "ENSG00000183155",
#     "ENSG00000154864",
#     "ENSG00000125285",
#     "ENSG00000100360",
#     "ENSG00000162924",
#     "ENSG00000241404",
#     "ENSG00000120833",
#     "ENSG00000237515",
#     "ENSG00000156103",
#     "ENSG00000179029",
#     "ENSG00000112319",
#     "ENSG00000113088",
#     "ENSG00000180871",
#     "ENSG00000105516",
#     "ENSG00000135218",
#     "ENSG00000109158",
#     "ENSG00000172936",
#     "ENSG00000120658",
#     "ENSG00000106178",
#     "ENSG00000147689",
#     "ENSG00000083099",
#     "ENSG00000170442",
#     "ENSG00000231074",
#     "ENSG00000135750",
#     "ENSG00000184076",
#     "ENSG00000005961",
#     "ENSG00000186867",
#     "ENSG00000180818",
#     "ENSG00000241794",
#     "ENSG00000196632",
#     "ENSG00000100644",
#     "ENSG00000285820",
#     "ENSG00000182134",
#     "ENSG00000079557",
#     "ENSG00000167618",
#     "ENSG00000169385",
#     "ENSG00000055955",
#     "ENSG00000174607",
#     "ENSG00000205045",
#     "ENSG00000121039",
#     "ENSG00000076554",
#     "ENSG00000121957",
#     "ENSG00000104921",
#     "ENSG00000270640",
#     "ENSG00000083896",
#     "ENSG00000024526",
#     "ENSG00000090432",
#     "ENSG00000184347",
#     "ENSG00000099860",
#     "ENSG00000132478",
#     "ENSG00000237906",
#     "ENSG00000101096",
#     "ENSG00000128683",
#     "ENSG00000102468",
#     "ENSG00000135439",
#     "ENSG00000002016",
#     "ENSG00000111252",
#     "ENSG00000138193",
#     "ENSG00000268170",
#     "ENSG00000188906",
#     "ENSG00000145649",
#     "ENSG00000168118",
#     "ENSG00000184979",
#     "ENSG00000108771",
#     "ENSG00000047457",
#     "ENSG00000131269",
#     "ENSG00000111605",
#     "ENSG00000037749",
#     "ENSG00000133742",
#     "ENSG00000130649",
#     "ENSG00000125355",
#     "ENSG00000310469",
#     "ENSG00000072682",
#     "ENSG00000129219",
#     "ENSG00000047936",
#     "ENSG00000013275",
#     "ENSG00000167634",
#     "ENSG00000215788",
#     "ENSG00000141425",
#     "ENSG00000145740",
#     "ENSG00000143494",
#     "ENSG00000201816",
#     "ENSG00000175938",
#     "ENSG00000076641",
#     "ENSG00000111729",
#     "ENSG00000153294",
#     "ENSG00000092964",
#     "ENSG00000104290",
#     "ENSG00000151789",
#     "ENSG00000174564",
#     "ENSG00000171604",
#     "ENSG00000196344",
#     "ENSG00000112977",
#     "ENSG00000166794",
#     "ENSG00000124299",
#     "ENSG00000141527",
#     "ENSG00000182450",
#     "ENSG00000178562",
#     "ENSG00000015520",
#     "ENSG00000165948",
#     "ENSG00000103355",
#     "ENSG00000177243",
#     "ENSG00000189298",
#     "ENSG00000103653",
#     "ENSG00000170035",
#     "ENSG00000104490",
#     "ENSG00000172482",
#     "ENSG00000196660",
#     "ENSG00000132676",
#     "ENSG00000136250",
#     "ENSG00000182185",
#     "ENSG00000112242",
#     "ENSG00000143384",
#     "ENSG00000146674",
#     "ENSG00000171903",
#     "ENSG00000141510",
#     "ENSG00000122026",
#     "ENSG00000105928",
#     "ENSG00000141480",
#     "ENSG00000131788"
#   ]
# }

# ---

query TargetAssociationsQuery {
    target(ensemblId: "ENSG00000105397") {
        id
        approvedSymbol
        associatedDiseases(
            page: { index: 0, size: 10 }
            orderByScore: "score"
            enableIndirect: false
            datasources: [
                {
                    id: "clinical_precedence"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "gwas_credible_sets"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "gene_burden"
                    weight: 1
                    propagate: true
                    required: false
                }
                { id: "eva", weight: 1, propagate: true, required: false }
                {
                    id: "genomics_england"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "gene2phenotype"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "uniprot_literature"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "uniprot_variants"
                    weight: 1
                    propagate: true
                    required: false
                }
                { id: "orphanet", weight: 1, propagate: true, required: false }
                { id: "clingen", weight: 1, propagate: true, required: false }
                {
                    id: "cancer_gene_census"
                    weight: 1
                    propagate: true
                    required: false
                }
                { id: "intogen", weight: 1, propagate: true, required: false }
                {
                    id: "eva_somatic"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "cancer_biomarkers"
                    weight: 1
                    propagate: true
                    required: false
                }
                {
                    id: "crispr_screen"
                    weight: 1
                    propagate: true
                    required: false
                }
                { id: "crispr", weight: 1, propagate: true, required: false }
                { id: "reactome", weight: 1, propagate: true, required: false }
                {
                    id: "europepmc"
                    weight: 0.2
                    propagate: true
                    required: false
                }
                {
                    id: "expression_atlas"
                    weight: 0.2
                    propagate: false
                    required: false
                }
                { id: "impc", weight: 0.2, propagate: true, required: false }
                {
                    id: "ot_crispr_validation"
                    weight: 0.5
                    propagate: true
                    required: false
                }
                {
                    id: "ot_crispr"
                    weight: 0.5
                    propagate: true
                    required: false
                }
                { id: "encore", weight: 0.5, propagate: true, required: false }
            ]
            Bs: []
            facetFilters: ["N4DS854BUCcyDrzNL72Y"]
            BFilter: ""
            includeMeasurements: false
        ) {
            count
            rows {
                novelty
                disease {
                    id
                    name
                }
                score
                datasourceScores {
                    id
                    score
                }
                datatypeScores {
                    id
                    score
                }
            }
        }
    }
}
