query study_single {
    studies(
        diseaseIds: ["MONDO_0004992"]
        enableIndirect: true
        page: { index: 0, size: 10 }
    ) {
        total
        items {
            id
            nSamples
            traitFromSource
            diseases {
                id
                name
                children {
                    id
                    name
                }
            }
        }
    }
}

# ---

query study_multiple {
    studies(
        studyIds: ["GCST90002357", "GCST004988", "GCST006979", "GCST90239655"]
        # filter: { studyId: { contains: "GCST" } }
        # search: "PLA"
        # sort: N_SAMPLES
        # dir: DESC
        page: { index: 0, size: 10 }
    ) {
        total
        items {
            id
            nSamples
            traitFromSource
        }
    }
}

# ---

query meta {
    meta {
        name
        product
        apiVersion {
            year
            month
            revision
        }
        dataVersion {
            year
            month
            revision
        }
        dataNamespace
        downloads
    }
}

# ---

query disease_with_evidence {
    disease(efoId: "EFO_0000266") {
        id
        name
        phenotypes(page: { index: 0, size: 1000 }) {
            total
            items {
                evidence {
                    aspect
                    bioCuration
                    diseaseFromSourceId
                    diseaseFromSource
                    frequency
                    modifiers {
                        id
                        name
                        description
                        namespace
                    }
                    onset {
                        id
                        name
                        description
                    }
                    sex
                }
                phenotypeHPO {
                    id
                    name
                    description
                    namespace
                }
                phenotypeEFO {
                    id
                    name
                }
            }
        }
    }
}

# ---

query search {
    search(
        queryString: "rheumatoid"
        page: { index: 0, size: 10 }
        entityNames: ["disease", "study"]
    ) {
        total
        hits {
            id
            name
            entity
            category
            description
            # keywords
            prefixes
            ngrams
            highlights
            multiplier
            score
            object {
                ... on Disease {
                    id
                    name
                    description
                }
                ... on Study {
                    id
                    publicationTitle
                }
            }
        }
        aggregations {
            total
            entities {
                name
                total
                categories {
                    name
                    total
                }
            }
        }
    }
}
